package goscan

import (
	"strings"
	"testing"
)

func TestIndexSharesASTAndResolvesRealLocalPackageNames(t *testing.T) {
	root := t.TempDir()
	write(t, root, "go.mod", "module example.com/index\n")
	write(t, root, "main.go", `package main
import "example.com/index/adapter/v2"
const Topic = wire.Topic
`)
	write(t, root, "adapter/v2/messages.go", "package wire\nconst Topic = \"orders\"\n")
	index, err := ReadWithOptions(root, ReadOptions{IncludeGenerated: true})
	if err != nil {
		t.Fatal(err)
	}
	files := index.PackageFiles(".")
	if len(files) != 1 || files[0].Imports["wire"] != "example.com/index/adapter/v2" {
		t.Fatalf("imports = %+v", files)
	}
	if index.ConstantString("example.com/index.Topic", nil) != "orders" {
		t.Fatal("real import name did not resolve")
	}
	again, err := PackageIndex(root, ".", index)
	if err != nil || again.PackageFiles(".")[0].Node != files[0].Node || again.Fset != index.Fset {
		t.Fatal("AST was reparsed")
	}
}

func TestBuildSelectionGeneratedCodeAndModuleBoundaries(t *testing.T) {
	root := t.TempDir()
	write(t, root, "go.mod", "module example.com/index\n")
	write(t, root, "app_linux.go", "package app\n")
	write(t, root, "app_windows.go", "package app\n")
	write(t, root, "feature.go", "//go:build custom\n\npackage app\n")
	write(t, root, "client.go", "// Code generated by fixture. DO NOT EDIT.\npackage app\n")
	write(t, root, "child/go.mod", "module example.com/child\n")
	write(t, root, "child/app.go", "package child\n")
	write(t, root, "testdata/invalid.go", "not Go source")
	index, err := ReadWithOptions(root, ReadOptions{GOOS: "linux", GOARCH: "amd64", IncludeGenerated: true, Tags: []string{"custom"}})
	if err != nil {
		t.Fatal(err)
	}
	if len(index.Files) != 3 {
		t.Fatalf("files = %+v", index.Files)
	}
	generated := 0
	for _, file := range index.Files {
		if file.Generated {
			generated++
		}
		if strings.Contains(file.Name, "windows") || strings.HasPrefix(file.Name, "child/") {
			t.Fatalf("foreign source selected: %s", file.Name)
		}
	}
	if generated != 1 {
		t.Fatalf("generated = %d", generated)
	}
	syntax, err := ReadWithOptions(root, ReadOptions{GOOS: "linux", GOARCH: "amd64"})
	if err != nil || len(syntax.Files) != 1 || syntax.Files[0].Name != "app_linux.go" {
		t.Fatalf("syntax source selection: %+v / %v", syntax, err)
	}
}
