package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/shortlink-org/portolan/catalog"
	"github.com/shortlink-org/portolan/internal/gohttp"
	"github.com/shortlink-org/portolan/plugin"
)

func writeHTTPFixture(t *testing.T, root, name, contents string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestExtractsRawGeneratedAndSOAPClients(t *testing.T) {
	root := t.TempDir()
	writeHTTPFixture(t, root, "go.mod", "module example.com/gateway\n")
	writeHTTPFixture(t, root, "partner/openapi.yaml", `openapi: 3.0.3
info:
  title: Partner API
  version: 1.2.0
paths:
  /v1/trips/{tripId}:
    get:
      operationId: getTrip
      tags: [trips]
`)
	writeHTTPFixture(t, root, "partner/client.gen.go", `// Code generated by oapi-codegen; DO NOT EDIT.
package partner
import (
  "context"
  "fmt"
  "net/http"
)
type Client struct{}
type ClientInterface interface { GetTrip(context.Context, string) (*http.Response, error) }
func NewGetTripRequest(server, tripID string) (*http.Request, error) {
  operationPath := fmt.Sprintf("/v1/trips/%s", tripID)
  return http.NewRequest(http.MethodGet, server+operationPath, nil)
}

`)
	writeHTTPFixture(t, root, "partner/adapter.go", `package partner
import "context"
func Load(ctx context.Context, c *Client, id string) error {
  _, err := c.GetTripWithResponse(ctx, id)
  return err
}
`)
	writeHTTPFixture(t, root, "core/update.go", `package core
import (
  "bytes"
  "context"
  "net/http"
)
const updatePath = "/v1/update"
func Update(ctx context.Context, baseURL string, body []byte) error {
  req, err := http.NewRequestWithContext(ctx, http.MethodPost, baseURL+updatePath, bytes.NewReader(body))
  if err != nil { return err }
  _ = req
  return nil
}
`)
	writeHTTPFixture(t, root, "transport/handler.go", `package transport
import (
  "context"
  "example.com/gateway/core"
)
func Handle(ctx context.Context, baseURL string, body []byte) error {
  return core.Update(ctx, baseURL, body)
}
`)
	writeHTTPFixture(t, root, "soap/cancel.go", `package soapclient
import (
  "context"
  soap "github.com/hooklift/gowsdl/soap"
)
const CancelAction = "urn:CancelBooking"
func Cancel(ctx context.Context, client soap.HTTPClient, request, response any) error {
  if request == nil {
    return nil
  }
  return client.CallContext(ctx, CancelAction, request, response)
}
`)
	writeHTTPFixture(t, root, "soap/booking.wsdl", `<?xml version="1.0"?>
<definitions name="BookingService" targetNamespace="urn:booking"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="urn:booking"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns="http://schemas.xmlsoap.org/wsdl/">
  <message name="CancelRequest"><part name="body" type="xsd:string"/></message>
  <message name="CancelResponse"><part name="body" type="xsd:string"/></message>
  <portType name="BookingPortType">
    <operation name="CancelBooking"><input message="tns:CancelRequest"/><output message="tns:CancelResponse"/></operation>
  </portType>
  <binding name="BookingBinding" type="tns:BookingPortType">
    <soap:binding style="document"/>
    <operation name="CancelBooking">
      <soap:operation soapAction="urn:CancelBooking"/>
    </operation>
  </binding>
  <service name="BookingService">
    <port name="BookingPort" binding="tns:BookingBinding">
      <soap:address location="https://booking.example/soap"/>
    </port>
  </service>
</definitions>
`)

	resp, err := extract(plugin.Input{Root: root, Commit: "abc", GeneratedAt: "2026-01-01T00:00:00Z"}, Options{Context: "edge", Service: "gateway"})
	if err != nil {
		t.Fatal(err)
	}
	var got catalog.Catalog
	if err := json.Unmarshal([]byte(resp.Files[0].Contents), &got); err != nil {
		t.Fatal(err)
	}
	service := got.Contexts[0].Services[0]
	if len(service.Consumes) != 3 {
		t.Fatalf("consumes = %+v", service.Consumes)
	}
	var generated, raw, soapCall *catalog.RpcCall
	for i := range service.Consumes {
		call := &service.Consumes[i]
		switch {
		case strings.Contains(call.ID, "getTrip"):
			generated = call
		case strings.Contains(call.ID, "POST /v1/update"):
			raw = call
		case strings.Contains(call.ID, "CancelBooking"):
			soapCall = call
		}
	}
	if generated == nil || generated.Status != catalog.StatusDeclared || generated.Peer != "partner" {
		t.Fatalf("generated = %+v", generated)
	}
	if raw == nil || raw.Status != catalog.StatusUnresolved || raw.Source != "core/update.go:9" {
		t.Fatalf("raw = %+v", raw)
	}
	if soapCall == nil || soapCall.Status != catalog.StatusDeclared || soapCall.Peer != "booking" {
		t.Fatalf("soap = %+v", soapCall)
	}
	if len(got.Externals) != 2 {
		t.Fatalf("externals = %+v", got.Externals)
	}
	if len(got.Flows) != 4 {
		t.Fatalf("flows = %+v", got.Flows)
	}
	var sawCondition, sawChain bool
	for _, flow := range got.Flows {
		for _, node := range flow.Steps {
			if step, ok := node.(*catalog.Step); ok && strings.Contains(step.Note, "request == nil") {
				sawCondition = true
			}
			if step, ok := node.(*catalog.Step); ok && strings.Contains(step.Note, "Handle → Update") {
				sawChain = true
			}
		}
	}
	if !sawCondition {
		t.Fatal("SOAP source condition was not preserved")
	}
	if !sawChain {
		t.Fatal("generic entry point was not followed to its outbound call")
	}
}

func TestFlowTracesConfigThroughConstructorFieldAndWrapper(t *testing.T) {
	root := t.TempDir()
	writeHTTPFixture(t, root, "go.mod", "module example.com/payments\n")
	writeHTTPFixture(t, root, "client/client.go", `package client
import (
  "context"
  "net/http"
	"net/url"
)
type Config struct { BaseURL string }
type Client struct { baseURL url.URL }
func Build(config map[string]string) (*Client, error) {
  return New(Config{BaseURL: config["url"]})
}
func New(cfg Config) (*Client, error) {
  parsed, err := url.Parse(cfg.BaseURL)
  if err != nil { return nil, err }
  return &Client{baseURL: *parsed}, nil
}
func (c *Client) request(ctx context.Context, method, path string) error {
  req, err := http.NewRequestWithContext(ctx, method, c.baseURL.String()+path, nil)
  if err != nil { return err }
  _ = req
  return nil
}
func (c *Client) Search(ctx context.Context) error {
  return c.request(ctx, http.MethodPost, "/v1/search")
}
`)

	resp, err := extract(plugin.Input{Root: root}, Options{Context: "pay", Service: "gateway"})
	if err != nil {
		t.Fatal(err)
	}
	var got catalog.Catalog
	if err := json.Unmarshal([]byte(resp.Files[0].Contents), &got); err != nil {
		t.Fatal(err)
	}
	if len(got.Flows) != 1 {
		t.Fatalf("flows = %+v", got.Flows)
	}
	flow := got.Flows[0]
	if flow.Name != "Client Search → outbound APIs" {
		t.Fatalf("flow name = %q", flow.Name)
	}
	step, ok := flow.Steps[0].(*catalog.Step)
	if !ok {
		t.Fatalf("step = %#v", flow.Steps[0])
	}
	if step.Label != "POST /v1/search" {
		t.Fatalf("step label = %q", step.Label)
	}
	if consumes := got.Contexts[0].Services[0].Consumes; len(consumes) != 1 || consumes[0].ID != "http-client/POST /v1/search" {
		t.Fatalf("consumes = %+v", consumes)
	}
	if !strings.Contains(step.Note, `config["url"] → Build → New → Client.baseURL → request URL`) {
		t.Fatalf("step note = %q", step.Note)
	}
	if !strings.Contains(step.Note, "Client.Search → Client.request") {
		t.Fatalf("step chain = %q", step.Note)
	}
}

func TestFlowKeepsDistinctCallsThroughClosureArguments(t *testing.T) {
	root := t.TempDir()
	writeHTTPFixture(t, root, "go.mod", "module example.com/closure\n")
	writeHTTPFixture(t, root, "client.go", `package closure
import (
  "context"
  "net/http"
)
func request(ctx context.Context, path string) error {
  req, err := http.NewRequestWithContext(ctx, http.MethodGet, "https://example.test"+path, nil)
  if err != nil { return err }
  _ = req
  return nil
}
func Refresh(ctx context.Context) {
  go func(path string) { _ = request(ctx, path) }("/v1/primary")
  go func(path string) { _ = request(ctx, path) }("/v1/secondary")
}
`)

	resp, err := extract(plugin.Input{Root: root}, Options{Context: "ops", Service: "refresher"})
	if err != nil {
		t.Fatal(err)
	}
	var got catalog.Catalog
	if err := json.Unmarshal([]byte(resp.Files[0].Contents), &got); err != nil {
		t.Fatal(err)
	}
	if len(got.Flows) != 1 {
		t.Fatalf("flows = %+v", got.Flows)
	}
	var labels []string
	for _, node := range got.Flows[0].Steps {
		if step, ok := node.(*catalog.Step); ok {
			labels = append(labels, step.Label)
		}
	}
	if strings.Join(labels, ",") != "GET /v1/primary,GET /v1/secondary" {
		t.Fatalf("labels = %+v", labels)
	}
}

func TestFlowDoesNotLinkMethodsByNameAlone(t *testing.T) {
	root := t.TempDir()
	writeHTTPFixture(t, root, "go.mod", "module example.com/close\n")
	writeHTTPFixture(t, root, "client.go", `package close
import "net/http"
type LocalCloser struct{}
func (LocalCloser) Close() error {
  _, err := http.Get("https://audit.example/v1/closed")
  return err
}
func Fetch() error {
  response, err := http.Get("https://data.example/v1/items")
  if err != nil { return err }
  defer response.Body.Close()
  return nil
}
`)

	resp, err := extract(plugin.Input{Root: root}, Options{Context: "edge", Service: "reader"})
	if err != nil {
		t.Fatal(err)
	}
	var got catalog.Catalog
	if err := json.Unmarshal([]byte(resp.Files[0].Contents), &got); err != nil {
		t.Fatal(err)
	}
	for _, flow := range got.Flows {
		if flow.Name != "Fetch → outbound APIs" {
			continue
		}
		if len(flow.Steps) != 1 {
			t.Fatalf("Fetch steps = %+v", flow.Steps)
		}
		step := flow.Steps[0].(*catalog.Step)
		if step.Label != "GET /v1/items" {
			t.Fatalf("Fetch step = %+v", step)
		}
		return
	}
	t.Fatalf("Fetch flow missing: %+v", got.Flows)
}

func TestOnlySourceBackedComplementsBecomeAnAlt(t *testing.T) {
	context := "edge"
	calls := []gohttp.Call{
		{Function: "choose", ID: "http-client/GET /one", Method: "GET", Path: "/one", Conditions: []string{"ready"}},
		{Function: "choose", ID: "http-client/GET /two", Method: "GET", Path: "/two", Conditions: []string{"not (ready)"}},
	}
	flows := flowsOf("edge.gateway", context, calls, Options{})
	if len(flows) != 1 || len(flows[0].Steps) != 1 {
		t.Fatalf("flows = %+v", flows)
	}
	alt, ok := flows[0].Steps[0].(*catalog.Alt)
	if !ok || alt.Branches[0].Title != "ready" || alt.Branches[1].Title != "not (ready)" {
		t.Fatalf("alt = %+v", flows[0].Steps[0])
	}

	calls[1].Conditions = nil
	flows = flowsOf("edge.gateway", context, calls, Options{})
	if _, ok := flows[0].Steps[0].(*catalog.Alt); ok {
		t.Fatal("unrelated calls became an alternative")
	}
}

func TestLearnsHandWrittenSOAPWrapperArgumentPositions(t *testing.T) {
	root := t.TempDir()
	writeHTTPFixture(t, root, "go.mod", "module example.com/checkout\n")
	writeHTTPFixture(t, root, "soap/booking.wsdl", `
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:booking" targetNamespace="urn:booking" name="Booking">
  <message name="CancelRequest"/><message name="CancelResponse"/>
  <portType name="BookingPortType"><operation name="Cancel"><input message="tns:CancelRequest"/><output message="tns:CancelResponse"/></operation></portType>
  <binding name="BookingBinding" type="tns:BookingPortType"><soap:binding style="document"/><operation name="Cancel"><soap:operation soapAction="urn:booking:cancel"/></operation></binding>
  <service name="BookingService"><port name="BookingPort" binding="tns:BookingBinding"><soap:address location="https://booking.example/soap"/></port></service>
</definitions>`)
	writeHTTPFixture(t, root, "soap/transport.go", `package soap
import "net/http"
type Transport struct{}
func (t *Transport) Call(actionBase, operation string, messageID string, query, reply any) error {
  req, err := http.NewRequest(http.MethodPost, "https://booking.example/soap", nil)
  if err != nil { return err }
  req.Header.Add("SOAPAction", actionBase+operation)
  return nil
}

type Service struct{ transport *Transport }
func (s *Service) Call(actionBase, operation string, query, reply any, stage string, options ...func()) error {
  return s.transport.Call(actionBase, operation, "message-id", query, reply)
}`)
	writeHTTPFixture(t, root, "checkout/cancel.go", `package checkout
import soapclient "example.com/checkout/soap"
const actionBase = "urn:booking:"
func CancelBooking(client *soapclient.Service, request, response any) error {
  return client.Call(actionBase, "cancel", request, response, "checkout")
}`)

	resp, err := extract(plugin.Input{Root: root}, Options{Context: "checkout", Service: "gateway"})
	if err != nil {
		t.Fatal(err)
	}
	var got catalog.Catalog
	if err := json.Unmarshal([]byte(resp.Files[0].Contents), &got); err != nil {
		t.Fatal(err)
	}
	service := got.Contexts[0].Services[0]
	if len(service.Consumes) != 1 {
		t.Fatalf("consumes = %+v", service.Consumes)
	}
	call := service.Consumes[0]
	if call.ID != "bookingservice.soap.BookingPort/Cancel" || call.Status != catalog.StatusDeclared || call.Source != "soap/booking.wsdl" {
		t.Fatalf("call = %+v", call)
	}
	if !strings.Contains(call.Note, "request 'request'") || !strings.Contains(call.Note, "response 'response'") {
		t.Fatalf("note = %q", call.Note)
	}
	if len(got.Flows) != 1 || got.Flows[0].Source != "checkout/cancel.go:4" {
		t.Fatalf("flows = %+v", got.Flows)
	}
}

func TestReadsSOAP12ActionFromContentType(t *testing.T) {
	root := t.TempDir()
	writeHTTPFixture(t, root, "go.mod", "module example.com/soap12\n")
	writeHTTPFixture(t, root, "contract.wsdl", `
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="urn:status" targetNamespace="urn:status" name="Status">
  <portType name="StatusPortType"><operation name="Check"/></portType>
	<binding name="Status11Binding" type="tns:StatusPortType"><soap:binding style="document"/><operation name="Check"><soap:operation soapAction="urn:status:check"/></operation></binding>
	<binding name="Status12Binding" type="tns:StatusPortType"><soap12:binding style="document"/><operation name="Check"><soap12:operation soapAction="urn:status:check"/></operation></binding>
	<service name="StatusService">
	  <port name="Status11Port" binding="tns:Status11Binding"><soap:address location="https://status.example/soap11"/></port>
	  <port name="Status12Port" binding="tns:Status12Binding"><soap12:address location="https://status.example/soap12"/></port>
	</service>
</definitions>`)
	writeHTTPFixture(t, root, "transport.go", `package soap12
import "net/http"
type Client struct{}
func (c *Client) Send(action string, request, response any) error {
  req, err := http.NewRequest(http.MethodPost, "https://status.example/soap", nil)
  if err != nil { return err }
  req.Header.Set("Content-Type", "application/soap+xml; charset=utf-8; action=\""+action+"\"")
  return nil
}
func Check(client *Client, request, response any) error {
  return client.Send("urn:status:check", request, response)
}`)

	resp, err := extract(plugin.Input{Root: root}, Options{Context: "monitoring", Service: "probe"})
	if err != nil {
		t.Fatal(err)
	}
	var got catalog.Catalog
	if err := json.Unmarshal([]byte(resp.Files[0].Contents), &got); err != nil {
		t.Fatal(err)
	}
	calls := got.Contexts[0].Services[0].Consumes
	if len(calls) != 1 || calls[0].ID != "statusservice.soap.Status12Port/Check" || calls[0].Status != catalog.StatusDeclared {
		t.Fatalf("calls = %+v", calls)
	}
	method := got.Externals[0].Provides[0].Methods[0]
	if method.SOAP == nil || method.SOAP.Version != "1.2" || method.SOAP.Action != "urn:status:check" {
		t.Fatalf("method = %+v", method)
	}
}
