package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/shortlink-org/portolan/catalog"
	"github.com/shortlink-org/portolan/internal/gohttp"
	"github.com/shortlink-org/portolan/plugin"
)

func writeHTTPFixture(t *testing.T, root, name, contents string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestExtractsRawGeneratedAndSOAPClients(t *testing.T) {
	root := t.TempDir()
	writeHTTPFixture(t, root, "go.mod", "module example.com/gateway\n")
	writeHTTPFixture(t, root, "partner/openapi.yaml", `openapi: 3.0.3
info:
  title: Partner API
  version: 1.2.0
paths:
  /v1/trips/{tripId}:
    get:
      operationId: getTrip
      tags: [trips]
`)
	writeHTTPFixture(t, root, "partner/client.gen.go", `// Code generated by oapi-codegen; DO NOT EDIT.
package partner
import (
  "context"
  "fmt"
  "net/http"
)
type Client struct{}
type ClientInterface interface { GetTrip(context.Context, string) (*http.Response, error) }
func NewGetTripRequest(server, tripID string) (*http.Request, error) {
  operationPath := fmt.Sprintf("/v1/trips/%s", tripID)
  return http.NewRequest(http.MethodGet, server+operationPath, nil)
}

`)
	writeHTTPFixture(t, root, "partner/adapter.go", `package partner
import "context"
func Load(ctx context.Context, c *Client, id string) error {
  _, err := c.GetTripWithResponse(ctx, id)
  return err
}
`)
	writeHTTPFixture(t, root, "core/update.go", `package core
import (
  "bytes"
  "context"
  "net/http"
)
const updatePath = "/v1/update"
func Update(ctx context.Context, baseURL string, body []byte) error {
  req, err := http.NewRequestWithContext(ctx, http.MethodPost, baseURL+updatePath, bytes.NewReader(body))
  if err != nil { return err }
  _ = req
  return nil
}
`)
	writeHTTPFixture(t, root, "transport/handler.go", `package transport
import (
  "context"
  "example.com/gateway/core"
)
func Handle(ctx context.Context, baseURL string, body []byte) error {
  return core.Update(ctx, baseURL, body)
}
`)
	writeHTTPFixture(t, root, "soap/cancel.go", `package soapclient
import (
  "context"
  soap "github.com/hooklift/gowsdl/soap"
)
const CancelAction = "urn:CancelBooking"
func Cancel(ctx context.Context, client soap.HTTPClient, request, response any) error {
  if request == nil {
    return nil
  }
  return client.CallContext(ctx, CancelAction, request, response)
}
`)
	writeHTTPFixture(t, root, "soap/booking.wsdl", `<?xml version="1.0"?>
<definitions name="BookingService" targetNamespace="urn:booking"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns="http://schemas.xmlsoap.org/wsdl/">
  <binding name="BookingBinding">
    <operation name="CancelBooking">
      <soap:operation soapAction="urn:CancelBooking"/>
    </operation>
  </binding>
  <service name="BookingService">
    <port name="BookingPort">
      <soap:address location="https://booking.example/soap"/>
    </port>
  </service>
</definitions>
`)

	resp, err := extract(plugin.Input{Root: root, Commit: "abc", GeneratedAt: "2026-01-01T00:00:00Z"}, Options{Context: "edge", Service: "gateway"})
	if err != nil {
		t.Fatal(err)
	}
	var got catalog.Catalog
	if err := json.Unmarshal([]byte(resp.Files[0].Contents), &got); err != nil {
		t.Fatal(err)
	}
	service := got.Contexts[0].Services[0]
	if len(service.Consumes) != 3 {
		t.Fatalf("consumes = %+v", service.Consumes)
	}
	var generated, raw, soapCall *catalog.RpcCall
	for i := range service.Consumes {
		call := &service.Consumes[i]
		switch {
		case strings.Contains(call.ID, "getTrip"):
			generated = call
		case strings.Contains(call.ID, "POST /v1/update"):
			raw = call
		case strings.Contains(call.ID, "CancelBooking"):
			soapCall = call
		}
	}
	if generated == nil || generated.Status != catalog.StatusDeclared || generated.Peer != "partner" {
		t.Fatalf("generated = %+v", generated)
	}
	if raw == nil || raw.Status != catalog.StatusUnresolved || raw.Source != "core/update.go:9" {
		t.Fatalf("raw = %+v", raw)
	}
	if soapCall == nil || soapCall.Status != catalog.StatusDeclared || soapCall.Peer != "bookingservice" {
		t.Fatalf("soap = %+v", soapCall)
	}
	if len(got.Externals) != 2 {
		t.Fatalf("externals = %+v", got.Externals)
	}
	if len(got.Flows) != 4 {
		t.Fatalf("flows = %+v", got.Flows)
	}
	var sawCondition, sawChain bool
	for _, flow := range got.Flows {
		for _, node := range flow.Steps {
			if step, ok := node.(*catalog.Step); ok && strings.Contains(step.Note, "request == nil") {
				sawCondition = true
			}
			if step, ok := node.(*catalog.Step); ok && strings.Contains(step.Note, "Handle → Update") {
				sawChain = true
			}
		}
	}
	if !sawCondition {
		t.Fatal("SOAP source condition was not preserved")
	}
	if !sawChain {
		t.Fatal("generic entry point was not followed to its outbound call")
	}
}

func TestOnlySourceBackedComplementsBecomeAnAlt(t *testing.T) {
	context := "edge"
	calls := []gohttp.Call{
		{Function: "choose", ID: "http-client/GET /one", Method: "GET", Path: "/one", Conditions: []string{"ready"}},
		{Function: "choose", ID: "http-client/GET /two", Method: "GET", Path: "/two", Conditions: []string{"not (ready)"}},
	}
	flows := flowsOf("edge.gateway", context, calls, Options{})
	if len(flows) != 1 || len(flows[0].Steps) != 1 {
		t.Fatalf("flows = %+v", flows)
	}
	alt, ok := flows[0].Steps[0].(*catalog.Alt)
	if !ok || alt.Branches[0].Title != "ready" || alt.Branches[1].Title != "not (ready)" {
		t.Fatalf("alt = %+v", flows[0].Steps[0])
	}

	calls[1].Conditions = nil
	flows = flowsOf("edge.gateway", context, calls, Options{})
	if _, ok := flows[0].Steps[0].(*catalog.Alt); ok {
		t.Fatal("unrelated calls became an alternative")
	}
}
