sequenceDiagram
    autonumber
    participant p0 as bus
    participant p1 as auth.auth
    participant p2 as auth-pg
    p0-)p1: PasswordChanged
    p1->>p1: EndAfterCredentialChange
    p1->>p2: ByUserID
    p1->>p2: ByID
    p1->>p2: Save
    p1-)p0: SessionEnded
