sequenceDiagram
    autonumber
    actor p0 as client
    participant p1 as shop.oms
    participant p2 as oms-pg
    participant p3 as bus
    p0->>p1: CancelOrder → CancelOrderResponse
    p1->>p2: SELECT
    p1->>p2: SELECT
    p1->>p2: UPDATE orders
    p1->>p2: DELETE
    p1->>p2: INSERT
    p1-)p3: OrderCancelled
    p1->>p2: SELECT
    p1->>p2: SELECT
