sequenceDiagram
    autonumber
    participant p0 as public.orders
    participant p1 as shop.oms-cdc
    participant p2 as Kafka
    p0->>p1: capture public.orders
    p1-)p2: publish shop.oms.public.orders.Envelope
