// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/shortlink-org/portolan/examples/auth/internal/application/policy"
	"github.com/shortlink-org/portolan/examples/auth/internal/application/session/usecases/end_after_credential_change"
	"github.com/shortlink-org/portolan/examples/auth/internal/application/session/usecases/login"
	"github.com/shortlink-org/portolan/examples/auth/internal/application/session/usecases/logout"
	"github.com/shortlink-org/portolan/examples/auth/internal/application/session/usecases/validate"
	"github.com/shortlink-org/portolan/examples/auth/internal/application/user/usecases/authenticate"
	"github.com/shortlink-org/portolan/examples/auth/internal/application/user/usecases/change_password"
	"github.com/shortlink-org/portolan/examples/auth/internal/application/user/usecases/get"
	"github.com/shortlink-org/portolan/examples/auth/internal/application/user/usecases/register"
	"github.com/shortlink-org/portolan/examples/auth/internal/di/provider"
	"github.com/shortlink-org/portolan/examples/auth/internal/infrastructure/repository/session"
	"github.com/shortlink-org/portolan/examples/auth/internal/infrastructure/repository/user"
	"github.com/shortlink-org/portolan/examples/auth/internal/infrastructure/transport/http"
	session2 "github.com/shortlink-org/portolan/examples/auth/internal/infrastructure/transport/http/session"
	user2 "github.com/shortlink-org/portolan/examples/auth/internal/infrastructure/transport/http/user"
	"github.com/shortlink-org/portolan/examples/auth/internal/pkg/messaging"
	"github.com/shortlink-org/portolan/examples/auth/internal/pkg/uow"
)

// Injectors from wire.go:

// New assembles the whole service.
//
// Everything below the handler - the database, repositories, buses, use cases,
// policies, the adapter between the two domains - is reachable only through the
// graph wire builds from these sets. A missing provider is a generation-time
// error rather than a nil dereference on the first request.
func New() (App, error) {
	config, err := provider.ProvideConfig()
	if err != nil {
		return App{}, err
	}
	logger, err := provider.ProvideLogger(config)
	if err != nil {
		return App{}, err
	}
	store, err := provider.ProvideStore(config, logger)
	if err != nil {
		return App{}, err
	}
	postgresStore, err := provider.ProvideDriver(store)
	if err != nil {
		return App{}, err
	}
	router, err := provider.ProvideRouter(postgresStore)
	if err != nil {
		return App{}, err
	}
	unitOfWork := uow.New(router)
	publisher, err := provider.ProvideOutboxPublisher()
	if err != nil {
		return App{}, err
	}
	userPublisher := user.NewPublisher(publisher)
	postgres := user.NewPostgres(router, unitOfWork, userPublisher)
	v := provider.ProvideNow()
	v2 := provider.ProvideNewID()
	useCase := register.New(postgres, v, v2)
	getUseCase := get.New(postgres)
	change_passwordUseCase := change_password.New(postgres, v)
	sessionPublisher := session.NewPublisher(publisher)
	sessionPostgres := session.NewPostgres(router, unitOfWork, sessionPublisher)
	cache, err := provider.ProvideCache(config)
	if err != nil {
		return App{}, err
	}
	duration := provider.ProvideCacheTTL(config)
	repository := provider.ProvideSessionRepository(sessionPostgres, cache, duration, v)
	validateUseCase := validate.New(repository, v)
	users := user2.NewUsers(useCase, getUseCase, change_passwordUseCase, validateUseCase)
	authenticateUseCase := authenticate.New(postgres)
	authenticator := provider.ProvideAuthenticator(authenticateUseCase)
	riskServiceClient, err := provider.ProvideRiskClient(config)
	if err != nil {
		return App{}, err
	}
	loginRisk := provider.ProvideRisk(riskServiceClient)
	loginUseCase := login.New(repository, authenticator, loginRisk, v, v2)
	logoutUseCase := logout.New(repository, v)
	sessions := session2.NewSessions(loginUseCase, logoutUseCase, validateUseCase)
	server := http.NewServer(users, sessions)
	handler := http.Router(server)
	backend := messaging.NewBackend(publisher, unitOfWork)
	client, err := provider.ProvideWatermill(config, logger, backend)
	if err != nil {
		return App{}, err
	}
	end_after_credential_changeUseCase := end_after_credential_change.New(repository, v)
	revokeSessionsOnPasswordChange := policy.New(end_after_credential_changeUseCase)
	relay, err := provider.ProvideRelay(store, logger, client, revokeSessionsOnPasswordChange)
	if err != nil {
		return App{}, err
	}
	app := App{
		Handler: handler,
		Driver:  postgresStore,
		Relay:   relay,
		Cache:   cache,
	}
	return app, nil
}
