// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/shortlink-org/portolan/examples/auth/internal/di/provider"
	"github.com/shortlink-org/portolan/examples/auth/internal/lockout/application/check"
	"github.com/shortlink-org/portolan/examples/auth/internal/lockout/application/record_failure"
	"github.com/shortlink-org/portolan/examples/auth/internal/lockout/application/record_success"
	"github.com/shortlink-org/portolan/examples/auth/internal/lockout/infrastructure/repository"
	"github.com/shortlink-org/portolan/examples/auth/internal/platform/messaging"
	"github.com/shortlink-org/portolan/examples/auth/internal/platform/uow"
	"github.com/shortlink-org/portolan/examples/auth/internal/session/application/end_after_credential_change"
	"github.com/shortlink-org/portolan/examples/auth/internal/session/application/login"
	"github.com/shortlink-org/portolan/examples/auth/internal/session/application/logout"
	"github.com/shortlink-org/portolan/examples/auth/internal/session/application/validate"
	"github.com/shortlink-org/portolan/examples/auth/internal/session/di"
	session2 "github.com/shortlink-org/portolan/examples/auth/internal/session/infrastructure/http"
	"github.com/shortlink-org/portolan/examples/auth/internal/session/infrastructure/identity"
	"github.com/shortlink-org/portolan/examples/auth/internal/session/infrastructure/messaging/policy"
	"github.com/shortlink-org/portolan/examples/auth/internal/session/infrastructure/repository"
	"github.com/shortlink-org/portolan/examples/auth/internal/transport/http"
	"github.com/shortlink-org/portolan/examples/auth/internal/user/application/change_password"
	"github.com/shortlink-org/portolan/examples/auth/internal/user/application/check_credentials"
	"github.com/shortlink-org/portolan/examples/auth/internal/user/application/get"
	"github.com/shortlink-org/portolan/examples/auth/internal/user/application/register"
	user2 "github.com/shortlink-org/portolan/examples/auth/internal/user/infrastructure/http"
	lockout2 "github.com/shortlink-org/portolan/examples/auth/internal/user/infrastructure/lockout"
	"github.com/shortlink-org/portolan/examples/auth/internal/user/infrastructure/password"
	"github.com/shortlink-org/portolan/examples/auth/internal/user/infrastructure/repository"
)

// Injectors from wire.go:

// New assembles the whole service.
//
// Everything below the handler - the database, repositories, buses, use cases,
// policies, the adapter between the two domains - is reachable only through the
// graph wire builds from these sets. A missing provider is a generation-time
// error rather than a nil dereference on the first request.
func New() (App, error) {
	config, err := provider.ProvideConfig()
	if err != nil {
		return App{}, err
	}
	logger, err := provider.ProvideLogger()
	if err != nil {
		return App{}, err
	}
	store, err := provider.ProvideStore(config, logger)
	if err != nil {
		return App{}, err
	}
	postgresStore, err := provider.ProvideDriver(store)
	if err != nil {
		return App{}, err
	}
	router, err := provider.ProvideRouter(postgresStore)
	if err != nil {
		return App{}, err
	}
	unitOfWork := uow.New(router)
	publisher, err := provider.ProvideOutboxPublisher()
	if err != nil {
		return App{}, err
	}
	userPublisher := user.NewPublisher(publisher)
	postgres := user.NewPostgres(router, unitOfWork, userPublisher)
	hasher := password.NewHasher()
	v := provider.ProvideNow()
	v2 := provider.ProvideNewID()
	useCase := register.New(postgres, hasher, v, v2)
	getUseCase := get.New(postgres)
	change_passwordUseCase := change_password.New(postgres, hasher, v)
	sessionPublisher := session.NewPublisher(publisher)
	sessionPostgres := session.NewPostgres(router, unitOfWork, sessionPublisher)
	cache, err := provider.ProvideCache(config)
	if err != nil {
		return App{}, err
	}
	duration := provider.ProvideCacheTTL(config)
	repository := di.ProvideRepository(sessionPostgres, cache, duration, v)
	validateUseCase := validate.New(repository, v)
	users := user2.NewUsers(useCase, getUseCase, change_passwordUseCase, validateUseCase)
	lockoutPublisher := lockout.NewPublisher(publisher)
	lockoutPostgres := lockout.NewPostgres(router, unitOfWork, lockoutPublisher)
	checkUseCase := check.New(lockoutPostgres, v)
	record_failureUseCase := record_failure.New(lockoutPostgres, v)
	record_successUseCase := record_success.New(lockoutPostgres, v)
	check_credentialsLockout := lockout2.New(checkUseCase, record_failureUseCase, record_successUseCase)
	check_credentialsUseCase := check_credentials.New(postgres, check_credentialsLockout, hasher)
	authenticator := identity.NewAuthenticator(check_credentialsUseCase)
	riskServiceClient, err := di.ProvideRiskClient(config)
	if err != nil {
		return App{}, err
	}
	risk := di.ProvideRisk(riskServiceClient)
	loginUseCase := login.New(repository, authenticator, risk, v, v2)
	logoutUseCase := logout.New(repository, v)
	sessions := session2.NewSessions(loginUseCase, logoutUseCase, validateUseCase)
	server := http.NewServer(users, sessions)
	handler := http.Router(server)
	backend := messaging.NewBackend(publisher, unitOfWork)
	client, err := provider.ProvideWatermill(config, logger, backend)
	if err != nil {
		return App{}, err
	}
	end_after_credential_changeUseCase := end_after_credential_change.New(repository, v)
	revokeSessionsOnPasswordChange := policy.New(end_after_credential_changeUseCase)
	buses := provider.ProvideBuses(revokeSessionsOnPasswordChange)
	relay, err := provider.ProvideRelay(store, logger, client, buses)
	if err != nil {
		return App{}, err
	}
	app := App{
		Handler: handler,
		Driver:  postgresStore,
		Relay:   relay,
		Cache:   cache,
	}
	return app, nil
}
