// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package register_test

import (
	"github.com/shortlink-org/portolan/examples/auth/internal/user/domain/vo/password"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordHasher creates a new instance of MockPasswordHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordHasher {
	mock := &MockPasswordHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordHasher is an autogenerated mock type for the PasswordHasher type
type MockPasswordHasher struct {
	mock.Mock
}

type MockPasswordHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordHasher) EXPECT() *MockPasswordHasher_Expecter {
	return &MockPasswordHasher_Expecter{mock: &_m.Mock}
}

// Hash provides a mock function for the type MockPasswordHasher
func (_mock *MockPasswordHasher) Hash(plaintext string) (password.Hash, error) {
	ret := _mock.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 password.Hash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (password.Hash, error)); ok {
		return returnFunc(plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(string) password.Hash); ok {
		r0 = returnFunc(plaintext)
	} else {
		r0 = ret.Get(0).(password.Hash)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordHasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockPasswordHasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - plaintext string
func (_e *MockPasswordHasher_Expecter) Hash(plaintext any) *MockPasswordHasher_Hash_Call {
	return &MockPasswordHasher_Hash_Call{Call: _e.mock.On("Hash", plaintext)}
}

func (_c *MockPasswordHasher_Hash_Call) Run(run func(plaintext string)) *MockPasswordHasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPasswordHasher_Hash_Call) Return(hash password.Hash, err error) *MockPasswordHasher_Hash_Call {
	_c.Call.Return(hash, err)
	return _c
}

func (_c *MockPasswordHasher_Hash_Call) RunAndReturn(run func(plaintext string) (password.Hash, error)) *MockPasswordHasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}
