// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package register_test

import (
	"context"

	"github.com/shortlink-org/portolan/examples/auth/internal/user/domain"
	"github.com/shortlink-org/portolan/examples/auth/internal/user/domain/event"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ByEmail provides a mock function for the type MockRepository
func (_mock *MockRepository) ByEmail(ctx context.Context, email string) (*user.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ByEmail")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByEmail'
type MockRepository_ByEmail_Call struct {
	*mock.Call
}

// ByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) ByEmail(ctx any, email any) *MockRepository_ByEmail_Call {
	return &MockRepository_ByEmail_Call{Call: _e.mock.On("ByEmail", ctx, email)}
}

func (_c *MockRepository_ByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepository_ByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ByEmail_Call) Return(user1 *user.User, err error) *MockRepository_ByEmail_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockRepository_ByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*user.User, error)) *MockRepository_ByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ByID provides a mock function for the type MockRepository
func (_mock *MockRepository) ByID(ctx context.Context, id string) (*user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type MockRepository_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) ByID(ctx any, id any) *MockRepository_ByID_Call {
	return &MockRepository_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *MockRepository_ByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ByID_Call) Return(user1 *user.User, err error) *MockRepository_ByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockRepository_ByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*user.User, error)) *MockRepository_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(ctx context.Context, u *user.User, events ...event.Event) error {
	var tmpRet mock.Arguments
	if len(events) > 0 {
		tmpRet = _mock.Called(ctx, u, events)
	} else {
		tmpRet = _mock.Called(ctx, u)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User, ...event.Event) error); ok {
		r0 = returnFunc(ctx, u, events...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - u *user.User
//   - events ...event.Event
func (_e *MockRepository_Expecter) Save(ctx any, u any, events ...any) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save",
		append([]any{ctx, u}, events...)...)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, u *user.User, events ...event.Event)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		var arg2 []event.Event
		var variadicArgs []event.Event
		if len(args) > 2 {
			variadicArgs = args[2].([]event.Event)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(err error) *MockRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(ctx context.Context, u *user.User, events ...event.Event) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
