export const CAPABILITIES: Record<string, { title: string; summary: string }> = {
  project: { title: "Component metadata", summary: "Name, ownership, repository and runnable commands." },
  "go-domain": { title: "Go domain model", summary: "Aggregates, entities, value objects and domain events." },
  "ts-domain": { title: "TypeScript domain model", summary: "Aggregates, entities, value objects and domain events." },
  "rust-domain": { title: "Rust domain model", summary: "Aggregates, entities, value objects and domain events." },
  "java-domain": { title: "Java domain model", summary: "Aggregates, entities, value objects and domain events." },
  "django-domain": { title: "Django data model", summary: "Models and their relationships." },
  "laravel-domain": { title: "Laravel data model", summary: "Eloquent models, events and listeners, routes and controllers." },
  "php-ddd": { title: "PHP DDD model", summary: "Bounded contexts laid out by module and hexagonal layer: aggregates, value objects, domain events, commands, queries, subscribers, Doctrine mappings." },
  openapi: { title: "HTTP API contract", summary: "Operations and messages declared by OpenAPI or Swagger." },
  wsdl: { title: "SOAP contract", summary: "Services, operations and messages declared by WSDL." },
  "http-clients": { title: "Outbound integrations", summary: "HTTP and SOAP calls, provider branches and code flows." },
  redis: { title: "Redis data model", summary: "Clients, key patterns and stored value hints." },
  river: { title: "River jobs", summary: "Job producers, workers and their code flows." },
  watermill: { title: "Watermill messaging", summary: "Publishers, handlers, topics and their code flows." },
  asyncapi: { title: "Messaging contract", summary: "Channels and messages declared by AsyncAPI." },
  celery: { title: "Celery jobs", summary: "Tasks, producers and worker flows." },
  graphql: { title: "GraphQL contract", summary: "Queries, mutations and schema types." },
  proto: { title: "Protobuf contract", summary: "gRPC services, methods and messages." },
  sql: { title: "SQL data model", summary: "Stores, tables, columns and relationships." },
  adr: { title: "Architecture decisions", summary: "ADRs and their catalog relationships." },
  rfc: { title: "Requests for comments", summary: "File-based RFC proposals, review state and architectural relationships." },
  "github-rfcs": { title: "GitHub RFCs", summary: "RFC proposals discussed as GitHub issues or pull requests." },
  glossary: { title: "Glossary", summary: "Project language and shared definitions." },
};
