// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package policy_test

import (
	"context"

	"github.com/shortlink-org/portolan/examples/auth/internal/session/application/end_after_credential_change/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionEnder creates a new instance of MockSessionEnder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionEnder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionEnder {
	mock := &MockSessionEnder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionEnder is an autogenerated mock type for the SessionEnder type
type MockSessionEnder struct {
	mock.Mock
}

type MockSessionEnder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionEnder) EXPECT() *MockSessionEnder_Expecter {
	return &MockSessionEnder_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockSessionEnder
func (_mock *MockSessionEnder) Handle(ctx context.Context, in dto.Input) error {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.Input) error); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionEnder_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockSessionEnder_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.Input
func (_e *MockSessionEnder_Expecter) Handle(ctx any, in any) *MockSessionEnder_Handle_Call {
	return &MockSessionEnder_Handle_Call{Call: _e.mock.On("Handle", ctx, in)}
}

func (_c *MockSessionEnder_Handle_Call) Run(run func(ctx context.Context, in dto.Input)) *MockSessionEnder_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.Input
		if args[1] != nil {
			arg1 = args[1].(dto.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionEnder_Handle_Call) Return(err error) *MockSessionEnder_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionEnder_Handle_Call) RunAndReturn(run func(ctx context.Context, in dto.Input) error) *MockSessionEnder_Handle_Call {
	_c.Call.Return(run)
	return _c
}
