// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package login_test

import (
	"context"

	"github.com/shortlink-org/portolan/examples/auth/internal/session/application/login"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRisk creates a new instance of MockRisk. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRisk(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRisk {
	mock := &MockRisk{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRisk is an autogenerated mock type for the Risk type
type MockRisk struct {
	mock.Mock
}

type MockRisk_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRisk) EXPECT() *MockRisk_Expecter {
	return &MockRisk_Expecter{mock: &_m.Mock}
}

// Assess provides a mock function for the type MockRisk
func (_mock *MockRisk) Assess(ctx context.Context, attempt login.Attempt) (login.Verdict, error) {
	ret := _mock.Called(ctx, attempt)

	if len(ret) == 0 {
		panic("no return value specified for Assess")
	}

	var r0 login.Verdict
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, login.Attempt) (login.Verdict, error)); ok {
		return returnFunc(ctx, attempt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, login.Attempt) login.Verdict); ok {
		r0 = returnFunc(ctx, attempt)
	} else {
		r0 = ret.Get(0).(login.Verdict)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, login.Attempt) error); ok {
		r1 = returnFunc(ctx, attempt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRisk_Assess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assess'
type MockRisk_Assess_Call struct {
	*mock.Call
}

// Assess is a helper method to define mock.On call
//   - ctx context.Context
//   - attempt login.Attempt
func (_e *MockRisk_Expecter) Assess(ctx any, attempt any) *MockRisk_Assess_Call {
	return &MockRisk_Assess_Call{Call: _e.mock.On("Assess", ctx, attempt)}
}

func (_c *MockRisk_Assess_Call) Run(run func(ctx context.Context, attempt login.Attempt)) *MockRisk_Assess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 login.Attempt
		if args[1] != nil {
			arg1 = args[1].(login.Attempt)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRisk_Assess_Call) Return(verdict login.Verdict, err error) *MockRisk_Assess_Call {
	_c.Call.Return(verdict, err)
	return _c
}

func (_c *MockRisk_Assess_Call) RunAndReturn(run func(ctx context.Context, attempt login.Attempt) (login.Verdict, error)) *MockRisk_Assess_Call {
	_c.Call.Return(run)
	return _c
}
