package main

import (
	"encoding/json"
	"net/url"
	"os"
	"path"
	"regexp"
	"slices"
	"strings"
	"testing"

	"github.com/shortlink-org/portolan/catalog"
	"github.com/shortlink-org/portolan/plugin"
)

var localLink = regexp.MustCompile(`\]\(([^\s)]+)(?:\s+[^)]*)?\)`)
var explicitAnchor = regexp.MustCompile(`<a id="([^"]+)"></a>`)

func fixtureCatalog(t *testing.T) catalog.Catalog {
	t.Helper()
	raw, err := os.ReadFile("testdata/catalog.json")
	if err != nil {
		t.Fatal(err)
	}
	var cat catalog.Catalog
	if err := json.Unmarshal(raw, &cat); err != nil {
		t.Fatal(err)
	}
	return cat
}

func renderedFiles(resp plugin.Response) map[string]string {
	out := make(map[string]string, len(resp.Files))
	for _, file := range resp.Files {
		out[file.Name] = file.Contents
	}
	return out
}

func TestEveryGeneratedLinkAndAnchorResolves(t *testing.T) {
	files := renderedFiles(render(plugin.Request{Catalog: fixtureCatalog(t)}, Options{}))
	for name, contents := range files {
		// This concatenation keeps each page's original relative links and names
		// the page in an HTML comment; it is not itself a linkable directory.
		if name == llmsFullPage {
			continue
		}
		for _, match := range localLink.FindAllStringSubmatch(contents, -1) {
			target := match[1]
			if strings.HasPrefix(target, "#") {
				target = name + target
			}
			if parsed, err := url.Parse(target); err != nil || parsed.IsAbs() {
				continue
			}
			parts := strings.SplitN(target, "#", 2)
			file := path.Clean(path.Join(path.Dir(name), parts[0]))
			body, ok := files[file]
			if !ok {
				t.Errorf("%s links to missing %s", name, target)
				continue
			}
			if len(parts) == 2 && parts[1] != "" && !hasAnchor(body, parts[1]) {
				t.Errorf("%s links to missing anchor %s in %s", name, parts[1], file)
			}
		}
	}
}

func hasAnchor(markdown, wanted string) bool {
	for _, match := range explicitAnchor.FindAllStringSubmatch(markdown, -1) {
		if match[1] == wanted {
			return true
		}
	}
	for _, line := range strings.Split(markdown, "\n") {
		if heading := strings.TrimLeft(line, "#"); heading != line && strings.HasPrefix(heading, " ") && anchor(strings.TrimSpace(heading)) == wanted {
			return true
		}
	}
	return false
}

func TestRenderingIgnoresNonSemanticEntityOrder(t *testing.T) {
	cat := fixtureCatalog(t)
	want := renderedFiles(render(plugin.Request{Catalog: cat}, Options{}))
	slices.Reverse(cat.Contexts)
	for i := range cat.Contexts {
		slices.Reverse(cat.Contexts[i].Services)
		for j := range cat.Contexts[i].Services {
			slices.Reverse(cat.Contexts[i].Services[j].Aggregates)
			slices.Reverse(cat.Contexts[i].Services[j].Provides)
			slices.Reverse(cat.Contexts[i].Services[j].Consumes)
		}
	}
	slices.Reverse(cat.Stores)
	slices.Reverse(cat.Modules)
	slices.Reverse(cat.Flows)
	slices.Reverse(cat.Adrs)
	slices.Reverse(cat.Terms)
	slices.Reverse(cat.Externals)
	got := renderedFiles(render(plugin.Request{Catalog: cat}, Options{}))
	if !reflectFiles(want, got) {
		t.Fatal("permuting entity sets changed the generated bytes")
	}
}

func reflectFiles(a, b map[string]string) bool {
	if len(a) != len(b) {
		return false
	}
	for name, value := range a {
		if b[name] != value {
			return false
		}
	}
	return true
}

func TestSemanticFieldsAndImmutableSourcesAreRendered(t *testing.T) {
	repo := "https://github.com/example/billing/blob/main"
	files := renderedFiles(render(plugin.Request{Catalog: fixtureCatalog(t)}, Options{SourceBaseURL: repo}))
	service := files["billing/invoices/README.md"]
	for _, want := range []string{"Schema modules", "Channels", "GET", "RaiseRequest", "server", "deprecated", "flow.raise-invoice#s3", repo + "/examples/billing/api/invoices.proto"} {
		if !strings.Contains(service, want) {
			t.Errorf("service page omits %q", want)
		}
	}
	if !strings.Contains(files["modules/example-billing.md"], "Billing contracts") {
		t.Error("module page was not generated")
	}
}

func TestExternalSourceUsesItsImmutablePin(t *testing.T) {
	owner := &catalog.Service{Repo: "gitlab.example/acme/payments", Path: "vendor/repos/acme/payments"}
	s := &site{cat: catalog.Catalog{Repos: []catalog.RepoPin{{Repo: owner.Repo, Commit: strings.Repeat("b", 40)}}}, opts: Options{SourceBaseURL: "https://github.com/example/billing/blob/main"}}
	got := s.source("billing/README.md", "vendor/repos/acme/payments/api/openapi.yaml:12", owner)
	want := "https://gitlab.example/acme/payments/-/blob/" + strings.Repeat("b", 40) + "/api/openapi.yaml#L12"
	if !strings.Contains(got, want) {
		t.Fatalf("source link = %s", got)
	}
}
