package main

import (
	"go/ast"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/shortlink-org/portolan/plugins/openapi"
)

// An HTTP client generated by oapi-codegen is read the way a gRPC client is:
// the tree already says which route each method calls. `New<Op>Request` builds
// the request, and its body names the path and the verb; the document the
// client was generated from is vendored beside it, and says which operation
// answers on that route and which interface it belongs to. Put together, a
// call on the client is `auth.v1.Sessions/login` - the same id the OpenAPI
// extractor gives the method on the other side, because both spell it with
// the same package.

// The four names a generated client is held by in a use case or an adapter.
var httpClientTypes = []string{"Client", "ClientInterface", "ClientWithResponses", "ClientWithResponsesInterface"}

// isHTTPClient says whether a package is one oapi-codegen generated a client
// into: a ClientInterface and at least one request builder.
func isHTTPClient(p *pkg) bool {
	var iface, builder bool
	for _, file := range p.files {
		for _, decl := range file.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					if ts, ok := spec.(*ast.TypeSpec); ok && ts.Name.Name == "ClientInterface" {
						if _, ok := ts.Type.(*ast.InterfaceType); ok {
							iface = true
						}
					}
				}
			case *ast.FuncDecl:
				if d.Recv == nil && requestBuilderOp(d.Name.Name) != "" {
					builder = true
				}
			}
		}
	}

	return iface && builder
}

// requestBuilderOp reads the operation's Go name off a request builder:
// NewLoginRequest and NewLoginRequestWithBody are both Login.
func requestBuilderOp(name string) string {
	rest, ok := strings.CutPrefix(name, "New")
	if !ok {
		return ""
	}
	if op, ok := strings.CutSuffix(rest, "RequestWithBody"); ok {
		return op
	}
	if op, ok := strings.CutSuffix(rest, "Request"); ok {
		return op
	}

	return ""
}

// readHTTPClient reads the routes the generated client calls and names them
// by the vendored document. The problem, when there is one, is a sentence
// for the reader of the diagnostics: no document beside the client, or a
// route the document does not declare.
func readHTTPClient(p *pkg) (map[string]client, string) {
	spec, source, problem := specBeside(p)
	if problem != "" {
		return nil, problem
	}

	c := client{pkg: spec.API, methods: map[string]string{}, source: source}
	var unknown []string
	for _, file := range p.files {
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv != nil {
				continue
			}
			op := requestBuilderOp(fn.Name.Name)
			if op == "" {
				continue
			}
			verb, path := routeOf(fn)
			if verb == "" || path == "" {
				continue
			}
			found, ok := spec.Find(verb, path)
			if !ok {
				unknown = append(unknown, verb+" "+path)

				continue
			}
			id := found.CallID(spec.API)
			// Every way the client offers the operation, to the same call.
			for _, variant := range []string{op, op + "WithBody", op + "WithResponse", op + "WithBodyWithResponse"} {
				c.methods[variant] = id
			}
		}
	}

	out := map[string]client{}
	for _, name := range httpClientTypes {
		out[name] = c
	}
	if len(unknown) > 0 {
		return out, "the client in " + p.dir + " calls " + strings.Join(unknown, ", ") + ", which the document beside it does not declare; those calls are left out"
	}

	return out, ""
}

// specBeside finds the document the client was generated from, in the same
// directory, and reads it.
func specBeside(p *pkg) (*openapi.Spec, string, string) {
	for _, name := range []string{"openapi.yaml", "openapi.yml", "swagger.yaml", "swagger.yml"} {
		path := filepath.Join(filepath.FromSlash(p.dir), name)
		if _, err := os.Stat(path); err != nil {
			continue
		}
		spec, err := openapi.Read(path)
		if err != nil {
			return nil, "", err.Error()
		}

		return spec, filepath.ToSlash(path), ""
	}

	return nil, "", "the client in " + p.dir + " has no openapi document beside it, so its calls cannot be named; vendor the document the client was generated from"
}

// routeOf reads the verb and path out of a request builder's body:
//
//	operationPath := fmt.Sprintf("/v1/users/%s", pathParam0)
//	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
func routeOf(fn *ast.FuncDecl) (verb, path string) {
	ast.Inspect(fn.Body, func(node ast.Node) bool {
		switch n := node.(type) {
		case *ast.AssignStmt:
			if len(n.Lhs) == 1 && len(n.Rhs) == 1 {
				if ident, ok := n.Lhs[0].(*ast.Ident); ok && ident.Name == "operationPath" {
					if call, ok := n.Rhs[0].(*ast.CallExpr); ok && len(call.Args) > 0 {
						if lit, ok := call.Args[0].(*ast.BasicLit); ok && lit.Kind == token.STRING {
							path, _ = strconv.Unquote(lit.Value)
						}
					}
				}
			}
		case *ast.CallExpr:
			if sel, ok := n.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "NewRequest" && len(n.Args) > 0 {
				switch arg := n.Args[0].(type) {
				case *ast.SelectorExpr:
					// http.MethodPost
					verb = strings.ToUpper(strings.TrimPrefix(arg.Sel.Name, "Method"))
				case *ast.BasicLit:
					if s, err := strconv.Unquote(arg.Value); err == nil {
						verb = strings.ToUpper(s)
					}
				}
			}
		}

		return true
	})

	return verb, path
}
