package extractgo

import (
	"reflect"
	"slices"
	"strings"
	"testing"

	"github.com/shortlink-org/portolan/catalog"
	"github.com/shortlink-org/portolan/internal/goscan"
)

// The readers below decide by what the declarations say a thing is, not by
// what it is called or where it sits. Each workspace is read as a real tree,
// because the types come from there.

func readWorkspace(t *testing.T, files map[string]string) (string, *goscan.Tree) {
	t.Helper()
	root := t.TempDir()
	writeTree(t, root, files)
	tree, err := goscan.ReadWithOptions(root, goscan.ReadOptions{IncludeGenerated: true, AllowPartial: true})
	if err != nil {
		t.Fatal(err)
	}

	return root, tree
}

// A server is what the generated code says it is - embedding
// Unimplemented<X>Server, or handed to Register<X>Server - in a package of
// any name.
func TestGRPCServersAreFoundByWhatTheGeneratedCodeSays(t *testing.T) {
	root, tree := readWorkspace(t, map[string]string{
		"go.mod": "module example.com/svc\n",
		"internal/api/gen/shop/v1/pricing_grpc.pb.go": `// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package pricingv1

const (
	Pricing_GetQuote_FullMethodName = "/shop.v1.Pricing/GetQuote"
	Legacy_Ping_FullMethodName      = "/shop.v1.Legacy/Ping"
)

type UnimplementedPricingServer struct{}

func RegisterPricingServer(s any, srv any) {}
func RegisterLegacyServer(s any, srv any)  {}
`,
		"internal/pricing/handlers/quote.go": `package handlers

import (
	"context"

	pricingv1 "example.com/svc/internal/api/gen/shop/v1"
)

type QuoteHandler struct {
	pricingv1.UnimplementedPricingServer
}

func (h *QuoteHandler) GetQuote(ctx context.Context, in *pricingv1.GetQuoteRequest) (*pricingv1.GetQuoteResponse, error) {
	return nil, nil
}

// Helper answers nothing the contract declares.
func (h *QuoteHandler) Helper(ctx context.Context, in *pricingv1.GetQuoteRequest) (*pricingv1.GetQuoteResponse, error) {
	return nil, nil
}
`,
		"internal/pricing/legacy/server.go": `package legacy

import (
	"context"

	pricingv1 "example.com/svc/internal/api/gen/shop/v1"
)

// Server predates the embed; the registration is what says it serves.
type Server struct{}

func NewServer() *Server { return &Server{} }

func (s *Server) Ping(ctx context.Context, in *pricingv1.PingRequest) (*pricingv1.PingResponse, error) {
	return nil, nil
}
`,
		"internal/pricing/lookalike/server.go": `package lookalike

import "context"

// ReportServer is named like a server and is not one.
type ReportServer struct{}

func (s *ReportServer) Ping(ctx context.Context, in *Request) (*Response, error) { return nil, nil }
`,
		"cmd/pricing/main.go": `package main

import (
	pricingv1 "example.com/svc/internal/api/gen/shop/v1"
	"example.com/svc/internal/pricing/handlers"
	"example.com/svc/internal/pricing/legacy"
)

func main() {
	var srv any
	pricingv1.RegisterPricingServer(srv, &handlers.QuoteHandler{})
	server := legacy.NewServer()
	pricingv1.RegisterLegacyServer(srv, server)
}
`,
	})

	var got []string
	for _, endpoint := range serviceEndpoints(root, "", tree) {
		got = append(got, endpoint.kind+" "+endpoint.label+" "+endpoint.entrypoint)
	}
	want := []string{
		"grpc shop.v1.Legacy/Ping internal/pricing/legacy:Server.Ping",
		"grpc shop.v1.Pricing/GetQuote internal/pricing/handlers:QuoteHandler.GetQuote",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("endpoints = %v, want %v", got, want)
	}

	layout := discoverLayout(root, tree)
	if !reflect.DeepEqual(layout.grpc, []string{"internal/pricing/handlers", "internal/pricing/legacy"}) {
		t.Errorf("grpc packages = %v", layout.grpc)
	}
	handlers, err := parsePkg(root, "internal/pricing/handlers", tree)
	if err != nil {
		t.Fatal(err)
	}
	if ref := grpcMethodRef(root, handlers, "QuoteHandler", "GetQuote"); ref != "shop.v1.Pricing/GetQuote" {
		t.Errorf("ref = %q", ref)
	}
}

// Two aggregates may each have a Cancel. Which one a use case calls is read
// off the type of what it calls it on, and a call whose receiver says
// nothing is left out when the name alone could be either.
func TestEmitsFollowTheReceiverTypeNotTheName(t *testing.T) {
	root, tree := readWorkspace(t, map[string]string{
		"go.mod": "module example.com/shop\n",
		"internal/order/domain/order.go": `package order

import "example.com/shop/internal/order/domain/event"

type Order struct{}

func (o *Order) Cancel() event.Cancelled { return event.Cancelled{} }

func (o *Order) Ship() event.Shipped { return event.Shipped{} }
`,
		"internal/order/domain/event/event.go": `package event

type Cancelled struct{}

type Shipped struct{}
`,
		"internal/delivery/domain/delivery.go": `package delivery

type Delivery struct{}

func (d *Delivery) Cancel() {}
`,
		"internal/order/application/cancel_delivery/usecase.go": `package cancel_delivery

import delivery "example.com/shop/internal/delivery/domain"

type Deliveries interface{ Get(id string) (*delivery.Delivery, error) }

type UseCase struct{ deliveries Deliveries }

func (uc *UseCase) Handle(id string) {
	d, _ := uc.deliveries.Get(id)
	d.Cancel()
}
`,
		"internal/order/application/cancel_order/usecase.go": `package cancel_order

import order "example.com/shop/internal/order/domain"

type Orders interface{ Get(id string) (*order.Order, error) }

type UseCase struct{ orders Orders }

func (uc *UseCase) Handle(id string) {
	o, _ := uc.orders.Get(id)
	o.Cancel()
}
`,
		"internal/order/application/untyped/usecase.go": `package untyped

func Handle(x interface{ Cancel(); Ship() }) {
	x.Cancel()
	x.Ship()
}
`,
	})
	domain, err := parsePkg(root, "internal/order/domain", tree)
	if err != nil {
		t.Fatal(err)
	}
	events := []catalog.Event{{ID: "shop.order.Cancelled", Name: "Cancelled"}, {ID: "shop.order.Shipped", Name: "Shipped"}}
	e := domainEmitters(domain, "Order", events, "example.com/shop/internal/order/domain", "example.com/shop/internal/delivery/domain")

	cases := map[string][]string{
		"internal/order/application/cancel_delivery": nil,
		"internal/order/application/cancel_order":    {"shop.order.Cancelled"},
		// Cancel could be the delivery's; Ship is only the order's.
		"internal/order/application/untyped": {"shop.order.Shipped"},
	}
	for dir, want := range cases {
		useCase, err := parsePkg(root, dir, tree)
		if err != nil {
			t.Fatal(err)
		}
		if got := e.useCaseEmits(useCase, "internal/order/domain"); !reflect.DeepEqual(got, want) {
			t.Errorf("%s: got %v, want %v", dir, got, want)
		}
	}
}

// An event's name is followed through constants wherever they are declared
// and however they are joined; one that cannot be followed keeps the event
// and says why its wire has no name.
func TestEventNamesResolveThroughConstants(t *testing.T) {
	root, tree := readWorkspace(t, map[string]string{
		"go.mod": "module example.com/shop\n",
		"internal/topics/topics.go": `package topics

const Base = "shop.order"

const Shipped = Base + ".shipped"
`,
		"internal/order/domain/event/names.go": `package event

const prefix = "shop.order."

const (
	TopicPlaced = prefix + "placed"
)
`,
		"internal/order/domain/event/events.go": `package event

import (
	"os"

	"example.com/shop/internal/topics"
)

type Placed struct{}

func (Placed) Name() string { return TopicPlaced }

type Shipped struct{}

func (Shipped) Name() string { return topics.Shipped }

type Dynamic struct{}

func (Dynamic) Name() string { return os.Getenv("TOPIC") }

// Label is a helper with a getter, not an event.
type Label struct{ name string }

func (l Label) Name() string { return l.name }
`,
	})
	pkg, err := parsePkg(root, "internal/order/domain/event", tree)
	if err != nil {
		t.Fatal(err)
	}
	var warnings []string
	events := readEvents(pkg, "shop.order.order", "", func(id, message string) { warnings = append(warnings, id+": "+message) })

	wires := map[string]string{}
	for _, event := range events {
		wires[event.Name] = ""
		if event.Wire != nil {
			wires[event.Name] = event.Wire.Name
		}
	}
	want := map[string]string{"Placed": "shop.order.placed", "Shipped": "shop.order.shipped", "Dynamic": ""}
	if !reflect.DeepEqual(wires, want) {
		t.Fatalf("wires = %v, want %v", wires, want)
	}
	if len(warnings) != 1 || !strings.HasPrefix(warnings[0], "shop.order.order.Dynamic: ") || !strings.Contains(warnings[0], "Dynamic.Name()") {
		t.Fatalf("warnings = %v", warnings)
	}
}

// A provider may hand its adapter back through a constructor, from another
// package, typed as the port; or allocate it with new and fill it in. Both
// are read off the declarations, so each method still reaches its use case.
func TestProviderAdaptersAreReadThroughConstructorsAndNew(t *testing.T) {
	useCases := map[string]string{
		"go.mod": "module example.com/app\n",
		"internal/application/user/usecases/authenticate/usecase.go": `package authenticate

type Lockout interface {
	Check()
	Failed()
}

type UseCase struct{ lockout Lockout }

func (uc *UseCase) Handle() { uc.lockout.Check(); uc.lockout.Failed() }
`,
		"internal/application/user/usecases/check/usecase.go": `package check

type UseCase struct{}

func (uc *UseCase) Handle() {}
`,
		"internal/application/user/usecases/record_failure/usecase.go": `package record_failure

type UseCase struct{}

func (uc *UseCase) Handle() {}
`,
	}
	providers := map[string]map[string]string{
		"constructor": {
			"internal/di/adapter/lockout.go": `package adapter

import (
	"example.com/app/internal/application/user/usecases/authenticate"
	"example.com/app/internal/application/user/usecases/check"
	"example.com/app/internal/application/user/usecases/record_failure"
)

type Lockout struct {
	check  *check.UseCase
	failed *record_failure.UseCase
}

func NewLockout(c *check.UseCase, f *record_failure.UseCase) authenticate.Lockout {
	return &Lockout{check: c, failed: f}
}

func (l *Lockout) Check()  { l.check.Handle() }
func (l *Lockout) Failed() { l.failed.Handle() }
`,
			"internal/di/provider.go": `package di

import (
	"example.com/app/internal/application/user/usecases/authenticate"
	"example.com/app/internal/application/user/usecases/check"
	"example.com/app/internal/application/user/usecases/record_failure"
	"example.com/app/internal/di/adapter"
)

func ProvideLockout(c *check.UseCase, f *record_failure.UseCase) authenticate.Lockout {
	return adapter.NewLockout(c, f)
}
`,
		},
		"new": {
			"internal/di/adapter.go": `package di

import (
	"example.com/app/internal/application/user/usecases/check"
	"example.com/app/internal/application/user/usecases/record_failure"
)

type lockoutAdapter struct {
	check  *check.UseCase
	failed *record_failure.UseCase
}

func (l *lockoutAdapter) Check()  { l.check.Handle() }
func (l *lockoutAdapter) Failed() { l.failed.Handle() }
`,
			"internal/di/provider.go": `package di

import (
	"example.com/app/internal/application/user/usecases/authenticate"
	"example.com/app/internal/application/user/usecases/check"
	"example.com/app/internal/application/user/usecases/record_failure"
)

func ProvideLockout(c *check.UseCase, f *record_failure.UseCase) authenticate.Lockout {
	l := new(lockoutAdapter)
	l.check, l.failed = c, f
	return l
}
`,
		},
	}
	for name, files := range providers {
		t.Run(name, func(t *testing.T) {
			all := map[string]string{}
			for rel, src := range useCases {
				all[rel] = src
			}
			for rel, src := range files {
				all[rel] = src
			}
			root, tree := readWorkspace(t, all)
			bound, ambiguous := readPortBindings(root, discoverLayout(root, tree))
			want := map[string]string{
				"user/authenticate.Lockout.Check":  "user/check",
				"user/authenticate.Lockout.Failed": "user/record_failure",
			}
			if !reflect.DeepEqual(bound, want) {
				t.Fatalf("bindings = %v, want %v", bound, want)
			}
			if !slices.Equal(ambiguous["user/authenticate.Lockout"], []string{"user/check", "user/record_failure"}) {
				t.Errorf("ambiguous = %v", ambiguous)
			}
		})
	}
}
