// The shared visual language - colours, line styles, arrow heads, the kinds
// of element and relation - and the specification block that declares it.

// --- shared visual language ------------------------------------------------
// These hex values are the light/dark-neutral midpoints of the --ctx-N and
// --status-* tokens in src/index.css. LikeC4 bakes colours into its own theme,
// so the seam between renderers is kept invisible by hand here.
export const CTX_COLORS = [
  "#4a86c8",
  "#9a66cc",
  "#2aa196",
  "#c4703f",
  "#6b7cb4",
  "#b46b8b",
];
export const STATUS_COLORS = {
  verified: "#2f9e63",
  declared: "#b8912f",
  unresolved: "#e0453f",
};
export const RESPONSE_ERROR_COLOR = "#b7646b";
export const STATUS_LINE = {
  verified: "solid",
  declared: "dashed",
  unresolved: "dotted",
};
export const STATUS_RANK = { verified: 0, declared: 1, unresolved: 2 };
export const KIND_HEAD = {
  event: "onormal",
  rpc: "normal",
  call: "none",
  response: "normal",
};

// Every relation carries the kind of fact it is, so a view can say which
// facts it draws: a level-2 picture with the bus on it leaves out the arrows
// that skip the bus, and nothing else has to change for it to do so.
export const RELATION_KINDS = [
  "publishes_to",
  "calls",
  "depends_on",
  "bus",
  "reads",
  "persists",
  "uses",
  "owns",
];

/** The colour token of a context: its place among the catalog's contexts. */
export function contextColorNameFor(catalog) {
  const contextColorName = (contextId) => {
    const i = catalog.contexts.findIndex((c) => c.id === contextId);
    return `ctx${(i < 0 ? 0 : i) % CTX_COLORS.length}`;
  };
  return contextColorName;
}

// ---------------------------------------------------------------------------
// specification
// ---------------------------------------------------------------------------
/** The specification block every view is drawn against. */
export function specificationSource() {
  const spec = [];
  spec.push(
    "// GENERATED by scripts/gen-likec4.mjs from the merged catalog — do not edit.",
  );
  spec.push("specification {");
  CTX_COLORS.forEach((hex, i) => spec.push(`  color ctx${i} ${hex}`));
  for (const [name, hex] of Object.entries(STATUS_COLORS)) {
    spec.push(`  color ${name} ${hex}`);
  }
  spec.push(`  color response_error ${RESPONSE_ERROR_COLOR}`);
  spec.push("");
  spec.push("  element context {");
  spec.push("    style { shape rectangle  opacity 5%  border dashed }");
  spec.push("  }");
  spec.push("  element service {");
  spec.push("    style { shape rectangle }");
  spec.push("  }");
  spec.push("  element aggregate {");
  spec.push("    style { shape rectangle  opacity 20% }");
  spec.push("  }");
  spec.push("  element event {");
  spec.push("    style { shape rectangle  opacity 30% }");
  spec.push("  }");
  spec.push("  element actor {");
  spec.push("    style { shape person  color muted }");
  spec.push("  }");
  spec.push("  element broker {");
  spec.push("    style { shape queue  color muted }");
  spec.push("  }");
  spec.push("  element store {");
  spec.push("    style { shape storage  color muted }");
  spec.push("  }");
  spec.push("  element external {");
  spec.push("    style { shape rectangle  color muted }");
  spec.push("  }");
  spec.push("  element unknown {");
  spec.push("    style { shape rectangle  color unresolved  border dashed }");
  spec.push("  }");
  spec.push("");
  // Where a service runs (portolan.0012): three nested places, drawn as
  // frames around the instances they hold, from the deployer's snapshot.
  spec.push("  deploymentNode environment {");
  spec.push("    style { shape rectangle  opacity 5%  border dashed }");
  spec.push("  }");
  spec.push("  deploymentNode cluster {");
  spec.push("    style { shape rectangle  opacity 10%  border dashed  color muted }");
  spec.push("  }");
  spec.push("  deploymentNode namespace {");
  spec.push("    style { shape rectangle  opacity 15%  color muted }");
  spec.push("  }");
  spec.push("");
  for (const kind of RELATION_KINDS) spec.push(`  relationship ${kind}`);
  spec.push("}");
  return spec;
}
