// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package record_failure_test

import (
	"context"

	"github.com/shortlink-org/portolan/examples/auth/internal/lockout/domain"
	"github.com/shortlink-org/portolan/examples/auth/internal/lockout/domain/event"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) ByUserID(ctx context.Context, userID string) (*lockout.Lockout, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ByUserID")
	}

	var r0 *lockout.Lockout
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*lockout.Lockout, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *lockout.Lockout); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lockout.Lockout)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByUserID'
type MockRepository_ByUserID_Call struct {
	*mock.Call
}

// ByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) ByUserID(ctx any, userID any) *MockRepository_ByUserID_Call {
	return &MockRepository_ByUserID_Call{Call: _e.mock.On("ByUserID", ctx, userID)}
}

func (_c *MockRepository_ByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_ByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ByUserID_Call) Return(lockout1 *lockout.Lockout, err error) *MockRepository_ByUserID_Call {
	_c.Call.Return(lockout1, err)
	return _c
}

func (_c *MockRepository_ByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*lockout.Lockout, error)) *MockRepository_ByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(ctx context.Context, l *lockout.Lockout, events ...event.Event) error {
	var tmpRet mock.Arguments
	if len(events) > 0 {
		tmpRet = _mock.Called(ctx, l, events)
	} else {
		tmpRet = _mock.Called(ctx, l)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lockout.Lockout, ...event.Event) error); ok {
		r0 = returnFunc(ctx, l, events...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - l *lockout.Lockout
//   - events ...event.Event
func (_e *MockRepository_Expecter) Save(ctx any, l any, events ...any) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save",
		append([]any{ctx, l}, events...)...)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, l *lockout.Lockout, events ...event.Event)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lockout.Lockout
		if args[1] != nil {
			arg1 = args[1].(*lockout.Lockout)
		}
		var arg2 []event.Event
		var variadicArgs []event.Event
		if len(args) > 2 {
			variadicArgs = args[2].([]event.Event)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(err error) *MockRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(ctx context.Context, l *lockout.Lockout, events ...event.Event) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
