// CI and publication recipes installed from Settings while Portolan is running
// locally. Every generated region identifies itself, so a later Portolan
// version can update its own work without taking ownership of the user's CI.

import { execFileSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import {
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve, sep } from "node:path";

const packageJson = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const VERSION = packageJson.version;
const GENERATED = "# Generated by Portolan. Preview changes in Settings before updating.";
const GITLAB_START = "# >>> Portolan delivery preset >>>";
const GITLAB_END = "# <<< Portolan delivery preset <<<";
const PROVIDERS = new Set(["github", "gitlab"]);
const FEATURE_IDS = ["check", "diff", "sarif", "pages"];
const DEFAULT_FEATURES = {
  github: ["check", "pages"],
  gitlab: ["pages"],
};
const FEATURE_DETAILS = {
  check: {
    label: "Architecture check",
    description: "Fail when committed architecture files are stale.",
  },
  diff: {
    label: "Pull-request architecture diff",
    description: "Post a sticky architecture summary where review happens.",
  },
  sarif: {
    label: "SARIF annotations",
    description: "Annotate changed architecture in GitHub's checks and code-scanning views.",
  },
  pages: {
    label: "Static catalog publishing",
    description: "Build and publish the catalog after changes reach the default branch.",
  },
};

function exists(path) {
  try { lstatSync(path); return true; } catch { return false; }
}

function git(workspace, args) {
  try {
    return execFileSync("git", args, {
      cwd: workspace,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
      timeout: 5_000,
    }).trim();
  } catch {
    return "";
  }
}

export function providerFromRemote(remote) {
  const value = String(remote ?? "").trim().toLowerCase();
  if (!value) return null;
  const host = /^(?:https?|ssh):\/\/(?:[^@/]+@)?([^/:]+)/.exec(value)?.[1]
    ?? /^[^@]+@([^:]+):/.exec(value)?.[1]
    ?? "";
  if (host === "github.com" || host.endsWith(".github.com")) return "github";
  if (host === "gitlab.com" || host.includes("gitlab")) return "gitlab";
  return null;
}

function repositoryName(remote, workspace) {
  const clean = String(remote ?? "").replace(/\/+$/, "").replace(/\.git$/, "");
  return clean.split(/[/:]/).filter(Boolean).pop() || relative(dirname(workspace), workspace) || "repository";
}

function defaultBranch(workspace) {
  const remoteHead = git(workspace, ["symbolic-ref", "--quiet", "--short", "refs/remotes/origin/HEAD"]);
  if (remoteHead.startsWith("origin/")) return remoteHead.slice("origin/".length);
  for (const candidate of ["main", "master"]) {
    if (git(workspace, ["rev-parse", "--verify", `refs/heads/${candidate}`])) return candidate;
  }
  return git(workspace, ["branch", "--show-current"]) || "main";
}

export function detectDeliveryForge(workspace) {
  const remote = git(workspace, ["config", "--get", "remote.origin.url"]);
  return {
    provider: providerFromRemote(remote),
    remote: remote || null,
    repository: repositoryName(remote, workspace),
    defaultBranch: defaultBranch(workspace),
  };
}

function githubCheck(branch) {
  return `${GENERATED}
name: Portolan architecture check

on:
  pull_request:
  push:
    branches: [${branch}]

permissions:
  contents: read

concurrency:
  group: portolan-check-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: shortlink-org/portolan@${VERSION}
        with:
          command: check
          version: ${VERSION}
`;
}

function githubPages(branch) {
  return `${GENERATED}
name: Publish Portolan catalog

on:
  push:
    branches: [${branch}]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: portolan-pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: shortlink-org/portolan@${VERSION}
        with:
          command: build
          version: ${VERSION}
          output: dist
          base: /\${{ github.event.repository.name }}/
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
`;
}

function githubDiff({ pages, sarif }) {
  const site = pages
    ? "\n          site: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
    : "";
  const sarifInput = sarif ? "\n          sarif-output: .portolan/diff.sarif" : "";
  const sarifPermission = sarif ? "\n  security-events: write # annotations in the checks tab" : "";
  const upload = sarif
    ? `
      - name: Annotate the checks tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: .portolan/diff.sarif
          category: architecture-diff
        # Fork pull requests have a read-only token; the Markdown summary still works.
        continue-on-error: true
`
    : "";
  return `${GENERATED}
name: Portolan architecture diff

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write${sarifPermission}

concurrency:
  group: portolan-diff-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  describe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: shortlink-org/portolan@${VERSION}
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        with:
          command: diff
          version: ${VERSION}
          base-ref: origin/\${{ github.base_ref }}
          head-ref: \${{ github.head_ref }}
          comment: true${site}${sarifInput}
${upload}`;
}

function gitlabCheck() {
  return `"portolan:check":
  stage: test
  tags:
    - runner-type:docker
  image:
    name: ghcr.io/shortlink-org/portolan:${VERSION}
    entrypoint: [""]
  variables:
    GIT_DEPTH: "0"
  script:
    - portolan check
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
`;
}

function gitlabDiff({ pages }) {
  const site = pages ? ' --site "$CI_PAGES_URL"' : "";
  return `"portolan:review":
  stage: test
  tags:
    - runner-type:docker
  image:
    name: ghcr.io/shortlink-org/portolan:${VERSION}
    entrypoint: [""]
  variables:
    GIT_DEPTH: "0"
  script:
    - portolan diff "origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --head "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"${site} --output .portolan/diff.md
    - cat .portolan/diff.md
    - portolan comment .portolan/diff.md
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
`;
}

function gitlabPages() {
  return `pages:
  stage: deploy
  tags:
    - runner-type:docker
  image:
    name: ghcr.io/shortlink-org/portolan:${VERSION}
    entrypoint: [""]
  variables:
    GIT_DEPTH: "0"
  script:
    - BASE_PATH="$(node -p 'new URL(process.env.CI_PAGES_URL).pathname.replace(/\\/?$/, "/") || "/"')"
    - portolan build --output public --base "$BASE_PATH"
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
`;
}

function gitlabBlock(features) {
  const jobs = [];
  if (features.has("check")) jobs.push(gitlabCheck());
  if (features.has("diff")) jobs.push(gitlabDiff({ pages: features.has("pages") }));
  if (features.has("pages")) jobs.push(gitlabPages());
  if (jobs.length === 0) return "";
  return `${GITLAB_START}\n${jobs.join("\n")}${GITLAB_END}\n`;
}

function mergeGitlab(existing, features) {
  const start = existing.indexOf(GITLAB_START);
  const end = existing.indexOf(GITLAB_END);
  if ((start === -1) !== (end === -1) || (start !== -1 && end < start)) {
    return { conflict: "The existing Portolan managed region is incomplete." };
  }
  if (start !== -1) {
    const after = end + GITLAB_END.length;
    const replacement = gitlabBlock(features).trimEnd();
    const content = `${existing.slice(0, start)}${replacement}${existing.slice(after)}`
      .replace(/\n{3,}/g, "\n\n")
      .replace(/^\n+|\n+$/g, "");
    return { content: content ? `${content}\n` : "" };
  }
  if (/^(?:["']?portolan:(?:check|review|pages)["']?|["']?pages["']?)\s*:/m.test(existing)) {
    return { conflict: "This pipeline already declares a Portolan job outside the managed region." };
  }
  const block = gitlabBlock(features);
  return { content: block ? `${existing.trimEnd()}${existing.trim() ? "\n\n" : ""}${block}` : existing };
}

function textDiff(path, before, after) {
  if (before === after) return "";
  const holder = mkdtempSync(join(tmpdir(), "portolan-preset-diff-"));
  const left = join(holder, "before");
  const right = join(holder, "after");
  try {
    writeFileSync(left, before);
    writeFileSync(right, after);
    let output = "";
    try {
      output = execFileSync("git", ["diff", "--no-index", "--no-ext-diff", "--unified=3", "--", left, right], {
        encoding: "utf8",
        maxBuffer: 2 * 1024 * 1024,
      });
    } catch (cause) {
      if (cause?.status !== 1) throw cause;
      output = String(cause.stdout ?? "");
    }
    return output
      .replaceAll(`a${left}`, `a/${path}`)
      .replaceAll(`b${right}`, `b/${path}`)
      .replaceAll(left, path)
      .replaceAll(right, path);
  } finally {
    rmSync(holder, { recursive: true, force: true });
  }
}

function readTarget(workspace, path) {
  const target = resolve(workspace, path);
  const root = resolve(workspace);
  if (target !== root && !target.startsWith(`${root}${sep}`)) throw new Error("Preset target must stay inside this repository.");
  let cursor = root;
  for (const segment of relative(root, target).split(sep).filter(Boolean)) {
    cursor = join(cursor, segment);
    if (exists(cursor) && lstatSync(cursor).isSymbolicLink()) return { exists: true, content: "", safe: false };
  }
  if (!exists(target)) return { exists: false, content: "", safe: true };
  const stat = lstatSync(target);
  if (!stat.isFile() || stat.isSymbolicLink()) return { exists: true, content: "", safe: false };
  if (stat.size > 512_000) return { exists: true, content: "", safe: false };
  const bytes = readFileSync(target);
  if (bytes.includes(0)) return { exists: true, content: "", safe: false };
  return { exists: true, content: bytes.toString("utf8"), safe: true };
}

function githubFile(workspace, path, content) {
  const current = readTarget(workspace, path);
  const managed = current.safe && current.content.startsWith(GENERATED);
  if (content === null) {
    if (!current.exists || !managed) return null;
    return {
      path,
      status: "removed",
      diff: textDiff(path, current.content, ""),
      current: current.content,
      next: "",
    };
  }
  const status = !current.exists ? "added" : !current.safe || !managed ? "conflict" : current.content === content ? "unchanged" : "changed";
  return {
    path,
    status,
    message: status === "conflict" ? "A file already exists here and was not created by Portolan." : undefined,
    diff: current.safe ? textDiff(path, current.content, content) : "Existing file is not a safe UTF-8 file.",
    current: current.content,
    next: content,
  };
}

function gitlabFile(workspace, features) {
  const path = ".gitlab-ci.yml";
  const current = readTarget(workspace, path);
  if (!current.safe) return { path, status: "conflict", message: "The existing pipeline is not a safe UTF-8 file.", diff: "", current: "", next: "" };
  const merged = mergeGitlab(current.content, features);
  if (merged.conflict) return { path, status: "conflict", message: merged.conflict, diff: "", current: current.content, next: "" };
  const status = current.content === merged.content ? "unchanged" : !current.exists ? "added" : "changed";
  return { path, status, diff: textDiff(path, current.content, merged.content), current: current.content, next: merged.content };
}

function revisionFor(provider, features, files) {
  const hash = createHash("sha256").update(provider);
  hash.update("\0"); hash.update([...features].sort().join(","));
  for (const file of files) {
    hash.update("\0"); hash.update(file.path); hash.update("\0"); hash.update(file.current); hash.update("\0"); hash.update(file.next);
  }
  return hash.digest("hex");
}

function deliveryRequest(request) {
  return typeof request === "string" || request == null ? { provider: request ?? undefined } : request;
}

function installedFeatures(workspace, provider) {
  const selected = new Set();
  if (provider === "github") {
    const check = readTarget(workspace, ".github/workflows/portolan-check.yml");
    const review = readTarget(workspace, ".github/workflows/portolan-review.yml");
    const pages = readTarget(workspace, ".github/workflows/portolan-pages.yml");
    if (check.safe && check.content.startsWith(GENERATED)) selected.add("check");
    if (review.safe && review.content.startsWith(GENERATED)) {
      selected.add("diff");
      if (review.content.includes("sarif-output:")) selected.add("sarif");
    }
    if (pages.safe && pages.content.startsWith(GENERATED)) selected.add("pages");
    return selected;
  }
  const pipeline = readTarget(workspace, ".gitlab-ci.yml");
  if (!pipeline.safe || !pipeline.content.includes(GITLAB_START)) return selected;
  const managed = pipeline.content.slice(
    pipeline.content.indexOf(GITLAB_START),
    pipeline.content.indexOf(GITLAB_END) + GITLAB_END.length,
  );
  if (/^[ \t]*["']?portolan:check["']?\s*:/m.test(managed)) selected.add("check");
  if (/^[ \t]*["']?portolan:review["']?\s*:/m.test(managed)) selected.add("diff");
  if (/^(?:["']?portolan:pages["']?|["']?pages["']?)\s*:/m.test(managed)) selected.add("pages");
  return selected;
}

function selectedFeatures(workspace, request, provider) {
  const installed = request.features == null ? installedFeatures(workspace, provider) : null;
  const raw = request.features == null
    ? installed.size > 0 ? [...installed] : DEFAULT_FEATURES[provider]
    : Array.isArray(request.features)
      ? request.features
      : String(request.features).split(",").filter(Boolean);
  const selected = new Set(raw);
  for (const feature of selected) {
    if (!FEATURE_IDS.includes(feature)) throw new Error(`Unknown delivery feature ${feature}.`);
  }
  if (selected.has("sarif")) selected.add("diff");
  if (provider !== "github" && selected.has("sarif")) {
    throw new Error("SARIF annotations are currently available only for GitHub.");
  }
  return selected;
}

function featureOptions(provider, selected) {
  return FEATURE_IDS.map((id) => ({
    id,
    ...FEATURE_DETAILS[id],
    selected: selected.has(id),
    available: id !== "sarif" || provider === "github",
    requires: id === "sarif" ? ["diff"] : [],
  }));
}

export function planDeliveryPreset(workspace, requested = {}) {
  const request = deliveryRequest(requested);
  const detected = detectDeliveryForge(workspace);
  const provider = request.provider || detected.provider || "github";
  if (!PROVIDERS.has(provider)) throw new Error("Delivery preset must be github or gitlab.");
  const features = selectedFeatures(workspace, request, provider);
  const files = provider === "github"
    ? [
        githubFile(workspace, ".github/workflows/portolan-check.yml", features.has("check") ? githubCheck(detected.defaultBranch) : null),
        githubFile(workspace, ".github/workflows/portolan-review.yml", features.has("diff") ? githubDiff({ pages: features.has("pages"), sarif: features.has("sarif") }) : null),
        githubFile(workspace, ".github/workflows/portolan-pages.yml", features.has("pages") ? githubPages(detected.defaultBranch) : null),
      ].filter(Boolean)
    : [gitlabFile(workspace, features)];
  const status = files.some((file) => file.status === "conflict")
    ? "conflict"
    : files.every((file) => file.status === "unchanged")
      ? "installed"
      : files.some((file) => ["removed", "unchanged"].includes(file.status))
          || files.some((file) => file.status === "changed" && (provider !== "gitlab" || file.current.includes(GITLAB_START)))
        ? "update"
        : "available";
  return {
    provider,
    detectedProvider: detected.provider,
    remote: detected.remote,
    repository: detected.repository,
    defaultBranch: detected.defaultBranch,
    status,
    revision: revisionFor(provider, features, files),
    features: featureOptions(provider, features),
    files,
  };
}

export function publicDeliveryPreset(plan) {
  return { ...plan, files: plan.files.map(({ current: _current, next: _next, ...file }) => file) };
}

export function installDeliveryPreset(workspace, request) {
  const selection = { provider: request.provider, features: request.features };
  const plan = planDeliveryPreset(workspace, selection);
  if (!request.revision || request.revision !== plan.revision) {
    const error = new Error("Files changed after this preset preview. Preview it again.");
    error.status = 409;
    throw error;
  }
  const conflict = plan.files.find((file) => file.status === "conflict");
  if (conflict) {
    const error = new Error(`${conflict.path}: ${conflict.message}`);
    error.status = 409;
    throw error;
  }
  for (const file of plan.files) {
    const current = readTarget(workspace, file.path);
    if (!current.safe || current.content !== file.current) {
      const error = new Error("Files changed after this preset preview. Preview it again.");
      error.status = 409;
      throw error;
    }
  }
  const written = [];
  for (const file of plan.files) {
    if (file.status === "unchanged") continue;
    const target = resolve(workspace, file.path);
    if (file.status === "removed") {
      rmSync(target);
      written.push(file.path);
      continue;
    }
    mkdirSync(dirname(target), { recursive: true });
    const temporary = join(dirname(target), `.portolan-${randomUUID()}.tmp`);
    try {
      writeFileSync(temporary, file.next, { flag: "wx" });
      renameSync(temporary, target);
    } finally {
      if (exists(temporary)) rmSync(temporary, { force: true });
    }
    written.push(file.path);
  }
  return { ...publicDeliveryPreset(planDeliveryPreset(workspace, selection)), written };
}
