// CI and publication recipes installed from Settings while Portolan is running
// locally. Every generated region identifies itself, so a later Portolan
// version can update its own work without taking ownership of the user's CI.

import { execFileSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import {
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve, sep } from "node:path";

const packageJson = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const VERSION = packageJson.version;
const GENERATED = "# Generated by Portolan. Preview changes in Settings before updating.";
const GITLAB_START = "# >>> Portolan delivery preset >>>";
const GITLAB_END = "# <<< Portolan delivery preset <<<";
const PROVIDERS = new Set(["github", "gitlab"]);

function exists(path) {
  try { lstatSync(path); return true; } catch { return false; }
}

function git(workspace, args) {
  try {
    return execFileSync("git", args, {
      cwd: workspace,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
      timeout: 5_000,
    }).trim();
  } catch {
    return "";
  }
}

export function providerFromRemote(remote) {
  const value = String(remote ?? "").trim().toLowerCase();
  if (!value) return null;
  const host = /^(?:https?|ssh):\/\/(?:[^@/]+@)?([^/:]+)/.exec(value)?.[1]
    ?? /^[^@]+@([^:]+):/.exec(value)?.[1]
    ?? "";
  if (host === "github.com" || host.endsWith(".github.com")) return "github";
  if (host === "gitlab.com" || host.includes("gitlab")) return "gitlab";
  return null;
}

function repositoryName(remote, workspace) {
  const clean = String(remote ?? "").replace(/\/+$/, "").replace(/\.git$/, "");
  return clean.split(/[/:]/).filter(Boolean).pop() || relative(dirname(workspace), workspace) || "repository";
}

function defaultBranch(workspace) {
  const remoteHead = git(workspace, ["symbolic-ref", "--quiet", "--short", "refs/remotes/origin/HEAD"]);
  if (remoteHead.startsWith("origin/")) return remoteHead.slice("origin/".length);
  for (const candidate of ["main", "master"]) {
    if (git(workspace, ["rev-parse", "--verify", `refs/heads/${candidate}`])) return candidate;
  }
  return git(workspace, ["branch", "--show-current"]) || "main";
}

export function detectDeliveryForge(workspace) {
  const remote = git(workspace, ["config", "--get", "remote.origin.url"]);
  return {
    provider: providerFromRemote(remote),
    remote: remote || null,
    repository: repositoryName(remote, workspace),
    defaultBranch: defaultBranch(workspace),
  };
}

function githubCheck(branch) {
  return `${GENERATED}
name: Portolan architecture check

on:
  pull_request:
  push:
    branches: [${branch}]

permissions:
  contents: read

concurrency:
  group: portolan-check-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: shortlink-org/portolan@${VERSION}
        with:
          command: check
          version: ${VERSION}
`;
}

function githubPages(branch) {
  return `${GENERATED}
name: Publish Portolan catalog

on:
  push:
    branches: [${branch}]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: portolan-pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: shortlink-org/portolan@${VERSION}
        with:
          command: build
          version: ${VERSION}
          output: dist
          base: /\${{ github.event.repository.name }}/
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
`;
}

function gitlabBlock() {
  return `${GITLAB_START}
"portolan:check":
  stage: .pre
  image:
    name: ghcr.io/shortlink-org/portolan:${VERSION}
    entrypoint: [""]
  variables:
    GIT_DEPTH: "0"
  script:
    - portolan check
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

"portolan:pages":
  stage: .post
  image:
    name: ghcr.io/shortlink-org/portolan:${VERSION}
    entrypoint: [""]
  variables:
    GIT_DEPTH: "0"
  script:
    - BASE_PATH="$(node -p 'new URL(process.env.CI_PAGES_URL).pathname.replace(/\\/?$/, "/") || "/"')"
    - portolan build --output dist --base "$BASE_PATH"
  pages:
    publish: dist
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
${GITLAB_END}
`;
}

function mergeGitlab(existing) {
  const start = existing.indexOf(GITLAB_START);
  const end = existing.indexOf(GITLAB_END);
  if ((start === -1) !== (end === -1) || (start !== -1 && end < start)) {
    return { conflict: "The existing Portolan managed region is incomplete." };
  }
  if (start !== -1) {
    const after = end + GITLAB_END.length;
    return { content: `${existing.slice(0, start)}${gitlabBlock().trimEnd()}${existing.slice(after)}`.replace(/\n*$/, "\n") };
  }
  if (/^[ \t]*["']?portolan:(?:check|pages)["']?\s*:/m.test(existing)) {
    return { conflict: "This pipeline already declares a Portolan job outside the managed region." };
  }
  return { content: `${existing.trimEnd()}${existing.trim() ? "\n\n" : ""}${gitlabBlock()}` };
}

function textDiff(path, before, after) {
  if (before === after) return "";
  const holder = mkdtempSync(join(tmpdir(), "portolan-preset-diff-"));
  const left = join(holder, "before");
  const right = join(holder, "after");
  try {
    writeFileSync(left, before);
    writeFileSync(right, after);
    let output = "";
    try {
      output = execFileSync("git", ["diff", "--no-index", "--no-ext-diff", "--unified=3", "--", left, right], {
        encoding: "utf8",
        maxBuffer: 2 * 1024 * 1024,
      });
    } catch (cause) {
      if (cause?.status !== 1) throw cause;
      output = String(cause.stdout ?? "");
    }
    return output
      .replaceAll(`a${left}`, `a/${path}`)
      .replaceAll(`b${right}`, `b/${path}`)
      .replaceAll(left, path)
      .replaceAll(right, path);
  } finally {
    rmSync(holder, { recursive: true, force: true });
  }
}

function readTarget(workspace, path) {
  const target = resolve(workspace, path);
  const root = resolve(workspace);
  if (target !== root && !target.startsWith(`${root}${sep}`)) throw new Error("Preset target must stay inside this repository.");
  let cursor = root;
  for (const segment of relative(root, target).split(sep).filter(Boolean)) {
    cursor = join(cursor, segment);
    if (exists(cursor) && lstatSync(cursor).isSymbolicLink()) return { exists: true, content: "", safe: false };
  }
  if (!exists(target)) return { exists: false, content: "", safe: true };
  const stat = lstatSync(target);
  if (!stat.isFile() || stat.isSymbolicLink()) return { exists: true, content: "", safe: false };
  if (stat.size > 512_000) return { exists: true, content: "", safe: false };
  const bytes = readFileSync(target);
  if (bytes.includes(0)) return { exists: true, content: "", safe: false };
  return { exists: true, content: bytes.toString("utf8"), safe: true };
}

function githubFile(workspace, path, content) {
  const current = readTarget(workspace, path);
  const managed = current.safe && current.content.startsWith(GENERATED);
  const status = !current.exists ? "added" : !current.safe || !managed ? "conflict" : current.content === content ? "unchanged" : "changed";
  return {
    path,
    status,
    message: status === "conflict" ? "A file already exists here and was not created by Portolan." : undefined,
    diff: current.safe ? textDiff(path, current.content, content) : "Existing file is not a safe UTF-8 file.",
    current: current.content,
    next: content,
  };
}

function gitlabFile(workspace) {
  const path = ".gitlab-ci.yml";
  const current = readTarget(workspace, path);
  if (!current.safe) return { path, status: "conflict", message: "The existing pipeline is not a safe UTF-8 file.", diff: "", current: "", next: "" };
  const merged = mergeGitlab(current.content);
  if (merged.conflict) return { path, status: "conflict", message: merged.conflict, diff: "", current: current.content, next: "" };
  const status = !current.exists ? "added" : current.content === merged.content ? "unchanged" : "changed";
  return { path, status, diff: textDiff(path, current.content, merged.content), current: current.content, next: merged.content };
}

function revisionFor(provider, files) {
  const hash = createHash("sha256").update(provider);
  for (const file of files) {
    hash.update("\0"); hash.update(file.path); hash.update("\0"); hash.update(file.current); hash.update("\0"); hash.update(file.next);
  }
  return hash.digest("hex");
}

export function planDeliveryPreset(workspace, requestedProvider) {
  const detected = detectDeliveryForge(workspace);
  const provider = requestedProvider || detected.provider || "github";
  if (!PROVIDERS.has(provider)) throw new Error("Delivery preset must be github or gitlab.");
  const files = provider === "github"
    ? [
        githubFile(workspace, ".github/workflows/portolan-check.yml", githubCheck(detected.defaultBranch)),
        githubFile(workspace, ".github/workflows/portolan-pages.yml", githubPages(detected.defaultBranch)),
      ]
    : [gitlabFile(workspace)];
  const status = files.some((file) => file.status === "conflict")
    ? "conflict"
    : files.every((file) => file.status === "unchanged")
      ? "installed"
      : files.some((file) => file.status === "changed") && (provider !== "gitlab" || files[0].current.includes(GITLAB_START))
        ? "update"
        : "available";
  return {
    provider,
    detectedProvider: detected.provider,
    remote: detected.remote,
    repository: detected.repository,
    defaultBranch: detected.defaultBranch,
    status,
    revision: revisionFor(provider, files),
    features: ["Validate generated architecture in reviews", "Publish the static catalog"],
    files,
  };
}

export function publicDeliveryPreset(plan) {
  return { ...plan, files: plan.files.map(({ current: _current, next: _next, ...file }) => file) };
}

export function installDeliveryPreset(workspace, request) {
  const plan = planDeliveryPreset(workspace, request.provider);
  if (!request.revision || request.revision !== plan.revision) {
    const error = new Error("Files changed after this preset preview. Preview it again.");
    error.status = 409;
    throw error;
  }
  const conflict = plan.files.find((file) => file.status === "conflict");
  if (conflict) {
    const error = new Error(`${conflict.path}: ${conflict.message}`);
    error.status = 409;
    throw error;
  }
  for (const file of plan.files) {
    const current = readTarget(workspace, file.path);
    if (!current.safe || current.content !== file.current) {
      const error = new Error("Files changed after this preset preview. Preview it again.");
      error.status = 409;
      throw error;
    }
  }
  const written = [];
  for (const file of plan.files) {
    if (file.status === "unchanged") continue;
    const target = resolve(workspace, file.path);
    mkdirSync(dirname(target), { recursive: true });
    const temporary = join(dirname(target), `.portolan-${randomUUID()}.tmp`);
    try {
      writeFileSync(temporary, file.next, { flag: "wx" });
      renameSync(temporary, target);
    } finally {
      if (exists(temporary)) rmSync(temporary, { force: true });
    }
    written.push(file.path);
  }
  return { ...publicDeliveryPreset(planDeliveryPreset(workspace, request.provider)), written };
}
