// Generates likec4/ sources from data/catalog.json.
//
// Everything LikeC4 renders is DECLARED here: the C4 views and one dynamic view
// per flow (plus a cross-context-only twin). Nothing in the app draws these
// pictures itself.
//
//   node scripts/gen-likec4.mjs

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const catalog = JSON.parse(readFileSync("data/catalog.json", "utf8"));

// --- ids (mirrors src/likec4/ids.ts; kept in step by src/likec4/ids.test.ts) ---
const safeId = (raw) => {
  const cleaned = raw.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
};
const fqn = (id) => id.split(".").map(safeId).join(".");
const flowViewId = (flow) => `flow_${safeId(flow.slug)}`;
const flowCrossViewId = (flow) => `${flowViewId(flow)}_cross`;
const contextViewId = (c) => `ctx_${safeId(c.id)}`;
const serviceViewId = (s) => `svc_${safeId(s.id)}`;

const q = (text) => `'${String(text).replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;

// --- shared visual language ------------------------------------------------
// These hex values are the light/dark-neutral midpoints of the --ctx-N and
// --status-* tokens in src/index.css. LikeC4 bakes colours into its own theme,
// so the seam between renderers is kept invisible by hand here.
const CTX_COLORS = ["#4a86c8", "#9a66cc", "#2aa196", "#c4703f", "#6b7cb4", "#b46b8b"];
const STATUS_COLORS = {
  verified: "#2f9e63",
  declared: "#b8912f",
  unresolved: "#e0453f",
};
const STATUS_LINE = { verified: "solid", declared: "dashed", unresolved: "dotted" };
const KIND_HEAD = { event: "onormal", rpc: "normal", call: "none" };

const contextColorName = (contextId) => {
  const i = catalog.contexts.findIndex((c) => c.id === contextId);
  return `ctx${(i < 0 ? 0 : i) % CTX_COLORS.length}`;
};

// --- collect participants that are not catalog services --------------------
const serviceIds = new Set(
  catalog.contexts.flatMap((c) => c.services.map((s) => s.id)),
);
const rootParticipants = new Map(); // id -> kind
for (const flow of catalog.flows) {
  for (const p of flow.participants) {
    if (serviceIds.has(p.id)) continue;
    rootParticipants.set(p.id, { kind: p.kind, label: p.label ?? p.id });
  }
}
// Event consumers that no service accounts for are real dependencies too.
for (const context of catalog.contexts) {
  for (const service of context.services) {
    for (const aggregate of service.aggregates) {
      for (const event of aggregate.events) {
        for (const consumer of event.consumers) {
          if (serviceIds.has(consumer.service)) continue;
          if (rootParticipants.has(consumer.service)) continue;
          rootParticipants.set(consumer.service, {
            kind: "unknown",
            label: consumer.service,
          });
        }
      }
    }
  }
}

// ---------------------------------------------------------------------------
// specification
// ---------------------------------------------------------------------------
const spec = [];
spec.push("// GENERATED by scripts/gen-likec4.mjs from data/catalog.json — do not edit.");
spec.push("specification {");
CTX_COLORS.forEach((hex, i) => spec.push(`  color ctx${i} ${hex}`));
for (const [name, hex] of Object.entries(STATUS_COLORS)) {
  spec.push(`  color ${name} ${hex}`);
}
spec.push("");
spec.push("  element context {");
spec.push("    style { shape rectangle  opacity 5%  border dashed }");
spec.push("  }");
spec.push("  element service {");
spec.push("    style { shape rectangle }");
spec.push("  }");
spec.push("  element aggregate {");
spec.push("    style { shape rectangle  opacity 20% }");
spec.push("  }");
spec.push("  element event {");
spec.push("    style { shape rectangle  opacity 30% }");
spec.push("  }");
spec.push("  element actor {");
spec.push("    style { shape person  color muted }");
spec.push("  }");
spec.push("  element broker {");
spec.push("    style { shape queue  color muted }");
spec.push("  }");
spec.push("  element store {");
spec.push("    style { shape storage  color muted }");
spec.push("  }");
spec.push("  element external {");
spec.push("    style { shape rectangle  color muted }");
spec.push("  }");
spec.push("  element unknown {");
spec.push("    style { shape rectangle  color unresolved  border dashed }");
spec.push("  }");
spec.push("}");

// ---------------------------------------------------------------------------
// model
// ---------------------------------------------------------------------------
const model = [];
model.push("model {");

for (const [id, meta] of rootParticipants) {
  model.push(`  ${safeId(id)} = ${meta.kind} ${q(meta.label)}`);
}
model.push("");

for (const context of catalog.contexts) {
  model.push(`  ${safeId(context.id)} = context ${q(context.name)} {`);
  model.push(`    description ${q(context.summary)}`);
  model.push(`    style { color ${contextColorName(context.id)} }`);
  for (const service of context.services) {
    model.push(`    ${safeId(service.slug)} = service ${q(service.name)} {`);
    model.push(`      description ${q(`${service.repo}/${service.path}`)}`);
    model.push(`      style { color ${contextColorName(context.id)} }`);
    for (const aggregate of service.aggregates) {
      model.push(`      ${safeId(aggregate.slug)} = aggregate ${q(aggregate.name)} {`);
      for (const event of aggregate.events) {
        const latest = event.versions[event.versions.length - 1];
        model.push(`        ${safeId(event.name)} = event ${q(event.name)} {`);
        model.push(`          description ${q(latest?.doc ?? "")}`);
        model.push("        }");
      }
      model.push("      }");
    }
    model.push("    }");
  }
  model.push("  }");
}
model.push("");

// relations: event consumption, then rpc calls
const relations = [];
for (const context of catalog.contexts) {
  for (const service of context.services) {
    for (const aggregate of service.aggregates) {
      for (const event of aggregate.events) {
        for (const consumer of event.consumers) {
          relations.push(
            `  ${fqn(service.id)} -> ${fqn(consumer.service)} ${q(event.name)} {\n` +
              `    style { color ${consumer.status}  line ${STATUS_LINE[consumer.status]}  head onormal }\n` +
              `  }`,
          );
        }
      }
    }
    for (const call of service.consumes) {
      if (!serviceIds.has(call.peer) && !rootParticipants.has(call.peer)) continue;
      const method = call.id.split("/").pop() ?? call.id;
      relations.push(
        `  ${fqn(service.id)} -> ${fqn(call.peer)} ${q(method)} {\n` +
          `    style { color ${call.status}  line ${STATUS_LINE[call.status]}  head normal }\n` +
          `  }`,
      );
    }
  }
}
model.push(...relations);
model.push("}");

// ---------------------------------------------------------------------------
// views
// ---------------------------------------------------------------------------

/**
 * LikeC4 dynamic views have `parallel` and `loop` but no `alt`. An alt branch is
 * therefore flattened into the sequence with its title carried on every step, so
 * the exclusivity is stated in words where it cannot be drawn as a frame.
 */
function emitSteps(nodes, out, indent, branchTitle) {
  for (const node of nodes) {
    if (node.type === "step") {
      const label = node.label ?? node.ref ?? node.kind;
      const title = branchTitle ? `[${branchTitle}] ${label}` : label;
      const attrs = [
        `color ${node.status}`,
        `line ${STATUS_LINE[node.status]}`,
        `head ${KIND_HEAD[node.kind]}`,
      ];
      const notes = [];
      if (branchTitle) notes.push(`alt branch: ${branchTitle}`);
      if (node.note) notes.push(node.note);
      if (node.line) notes.push(node.line);
      out.push(
        `${indent}${fqn(node.from)} -> ${fqn(node.to)} ${q(title)} {`,
      );
      out.push(`${indent}  ${attrs.join("  ")}`);
      if (notes.length > 0) out.push(`${indent}  notes ${q(notes.join(" — "))}`);
      out.push(`${indent}}`);
      continue;
    }
    if (node.type === "parallel") {
      out.push(`${indent}parallel {`);
      for (const branch of node.branches) emitSteps(branch, out, `${indent}  `, branchTitle);
      out.push(`${indent}}`);
      continue;
    }
    if (node.type === "loop") {
      out.push(`${indent}loop ${q(node.title)} {`);
      emitSteps(node.steps, out, `${indent}  `, branchTitle);
      out.push(`${indent}}`);
      continue;
    }
    if (node.type === "alt") {
      for (const branch of node.branches) {
        emitSteps(branch.steps, out, indent, branch.title);
      }
    }
  }
}

/** Keeps only steps that actually leave a bounded context. */
function crossContextOnly(nodes, contextOf) {
  const keep = (step) => {
    if (step.kind === "call") return false;
    if (step.from === step.to) return false;
    const a = contextOf(step.from);
    const b = contextOf(step.to);
    return !(a !== null && a === b);
  };
  const walk = (list) => {
    const out = [];
    for (const node of list) {
      if (node.type === "step") {
        if (keep(node)) out.push(node);
      } else if (node.type === "parallel") {
        const branches = node.branches.map(walk).filter((b) => b.length > 0);
        if (branches.length > 0) out.push({ ...node, branches });
      } else if (node.type === "loop") {
        const steps = walk(node.steps);
        if (steps.length > 0) out.push({ ...node, steps });
      } else if (node.type === "alt") {
        const branches = node.branches
          .map((b) => ({ ...b, steps: walk(b.steps) }))
          .filter((b) => b.steps.length > 0);
        if (branches.length > 0) out.push({ ...node, branches });
      }
    }
    return out;
  };
  return walk(nodes);
}

const views = [];
views.push("views {");
// No landscape view: the system-wide dependency picture belongs to React Flow
// at /graph, and no picture may be drawn by both renderers.
for (const context of catalog.contexts) {
  views.push(`  view ${contextViewId(context)} of ${safeId(context.id)} {`);
  views.push(`    title ${q(context.name)}`);
  views.push("    include *");
  views.push("  }");
  for (const service of context.services) {
    views.push(`  view ${serviceViewId(service)} of ${fqn(service.id)} {`);
    views.push(`    title ${q(service.name)}`);
    views.push("    include *, -> *, * ->");
    views.push("  }");
  }
}
views.push("");

for (const flow of catalog.flows) {
  const contexts = new Map(flow.participants.map((p) => [p.id, p.context]));
  const contextOf = (id) => contexts.get(id) ?? null;

  views.push(`  dynamic view ${flowViewId(flow)} {`);
  views.push(`    title ${q(flow.name)}`);
  views.push(`    description ${q(flow.summary)}`);
  const body = [];
  emitSteps(flow.steps, body, "    ", null);
  views.push(...body);
  views.push("  }");
  views.push("");

  const cross = crossContextOnly(flow.steps, contextOf);
  views.push(`  dynamic view ${flowCrossViewId(flow)} {`);
  views.push(`    title ${q(`${flow.name} — crossings only`)}`);
  const crossBody = [];
  emitSteps(cross, crossBody, "    ", null);
  if (crossBody.length === 0) {
    // A flow with no crossing at all still needs a renderable view.
    const first = flow.participants[0];
    if (first) crossBody.push(`    ${fqn(first.id)} -> ${fqn(first.id)} 'no cross-context step'`);
  }
  views.push(...crossBody);
  views.push("  }");
  views.push("");
}
views.push("}");

mkdirSync("likec4", { recursive: true });
writeFileSync("likec4/spec.c4", `${spec.join("\n")}\n`);
writeFileSync("likec4/model.c4", `// GENERATED — do not edit.\n${model.join("\n")}\n`);
writeFileSync("likec4/views.c4", `// GENERATED — do not edit.\n${views.join("\n")}\n`);

console.log(
  `wrote likec4/spec.c4, likec4/model.c4, likec4/views.c4 ` +
    `(${catalog.flows.length * 2} dynamic views, ${relations.length} relations)`,
);
