import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, expect, it } from "vitest";
import { discoverProject } from "./local-discovery.mjs";

const roots = [];
afterEach(() => roots.splice(0).forEach((root) => rmSync(root, { recursive: true, force: true })));
function discover(files) {
  const root = mkdtempSync(join(tmpdir(), "portolan-go-discovery-"));
  roots.push(root);
  for (const [name, text] of Object.entries({ "go.mod": "module example.com/app\n", ...files })) {
    const path = join(root, name);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, text);
  }
  return discoverProject(root, ".").detections.map((item) => item.plugin);
}
it("offers Go flows and SQL for a service without any DDD directories", () => {
  expect(discover({
    "web/routes.go": 'package web\nimport "net/http"\nfunc Register(m *http.ServeMux) { m.HandleFunc("POST /orders", create) }',
    "store/migrations/001.sql": "CREATE TABLE orders (id uuid PRIMARY KEY);",
  })).toEqual(expect.arrayContaining(["go-domain", "sql"]));
});
it("does not offer Go domain extraction for unregistered helpers or generated handlers", () => {
  for (const source of [
    'package web\nimport "net/http"\nfunc Help(w http.ResponseWriter, r *http.Request) {}',
    '// Code generated by fixture. DO NOT EDIT.\npackage web\nimport "net/http"\nfunc Register() { http.HandleFunc("/x", help) }',
  ]) expect(discover({ "web/routes.go": source })).not.toContain("go-domain");
});
