// Composes the JSON Schema for portolan.json out of what the plugins say about
// themselves.
//
//   node scripts/schema.mjs            write schema/portolan.schema.json
//   node scripts/schema.mjs --check    fail if the schema on disk is not what
//                                      the plugins describe now
//
// The manifest tells each plugin the things its source cannot carry - which
// bounded context a Go module belongs to, whose proto package a client calls.
// Only the plugin knows what it can be told, so it is asked, and the answers
// are composed into one document keyed by the name the manifest declares each
// plugin under. An editor reads it while the file is being written; `gen` reads
// it before running anything.
//
// The result is committed, which is what keeps `gen` from having to ask four
// plugins the same question on every run. `--check` in CI is what keeps the
// committed copy honest.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

import { describePlugin } from "./plugin-host.mjs";

const OUT = "schema/portolan.schema.json";

const check = process.argv.includes("--check");
const manifest = JSON.parse(readFileSync("portolan.json", "utf8"));

const described = new Map();
for (const plugin of manifest.plugins ?? []) {
  let descriptor;
  try {
    descriptor = await describePlugin(plugin);
  } catch (cause) {
    fail(`plugin ${plugin.name} could not be asked what it is: ${cause.message}`);
  }

  if (!descriptor) {
    // A plugin from before this part of the protocol existed. Naming it in the
    // manifest is not an error; it just means its options are the one thing
    // here nothing can check.
    console.warn(
      `  ${plugin.name} does not describe itself, so its options are not checked`,
    );
  }

  described.set(plugin.name, descriptor);
}

const composed = `${JSON.stringify(compose(), null, 2)}\n`;

let current = null;
try {
  current = readFileSync(OUT, "utf8");
} catch {
  // Absent, which is the same as out of date.
}

if (current === composed) {
  console.log(`${OUT}: up to date`);
} else if (check) {
  console.error(
    `${OUT} is ${current === null ? "missing" : "out of date"}. Run \`npm run schema\`.`,
  );
  process.exit(1);
} else {
  mkdirSync("schema", { recursive: true });
  writeFileSync(OUT, composed);
  console.log(`${OUT}: written from ${described.size} plugin${described.size === 1 ? "" : "s"}`);
}

function compose() {
  const defs = {};
  for (const [name, descriptor] of described) {
    if (descriptor?.options) defs[optionsKey(name)] = descriptor.options;
  }

  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://github.com/shortlink-org/portolan/schema/portolan.schema.json",
    title: "portolan manifest",
    description:
      "Where the facts come from, what produces them, and what turns them into something to read. Generated by scripts/schema.mjs from the plugins this manifest declares; run `npm run schema` after changing them.",
    type: "object",
    additionalProperties: false,
    required: ["sources"],
    properties: {
      $schema: { type: "string" },
      $comment: { type: "string" },
      sources: {
        type: "array",
        minItems: 1,
        items: { type: "string" },
        description:
          "Globs of the catalog fragments that make up the estate. They are merged, then validated as a union, so a fragment naming a peer it does not own is normal rather than broken.",
      },
      plugins: {
        type: "array",
        items: { $ref: "#/$defs/plugin" },
        description: "How to run each plugin. A step names one by the name declared here.",
      },
      extract: {
        type: "array",
        items: step("extract"),
        description: "Steps that read source and write catalog fragments. They run first, before there is a catalog.",
      },
      verify: {
        type: "array",
        items: step("verify"),
        description:
          "Steps that read something observed - traces, a test's record - and answer with a fragment about the catalog somebody else declared.",
      },
      generate: {
        type: "array",
        items: step("generate"),
        description: "Steps that read the merged catalog and write something to read.",
      },
    },
    $defs: {
      plugin: {
        type: "object",
        additionalProperties: false,
        required: ["name"],
        oneOf: [{ required: ["wasm"] }, { required: ["process"] }],
        properties: {
          name: {
            type: "string",
            description: "What the steps below call this plugin. It need not be the plugin's own name.",
          },
          wasm: {
            type: "object",
            additionalProperties: false,
            required: ["url"],
            description:
              "The default. The module gets no filesystem, no network and no environment, so a plugin from somebody else's repository can be run over your source tree without reading it.",
            properties: {
              url: {
                type: "string",
                pattern: "^(https://|file://)",
                description:
                  "https:// to download, or file:// for a path beside the manifest, as in file://plugins/gen-markdown.wasm.",
              },
              sha256: {
                type: "string",
                pattern: "^[0-9a-f]{64}$",
                description:
                  "Checksum of the module. Required for a download; optional for a local file, which it does not protect.",
              },
            },
          },
          process: {
            type: "object",
            additionalProperties: false,
            required: ["cmd"],
            description:
              "The escape hatch for a plugin that needs a toolchain. Same protocol, none of the sandbox, which is the trade being made.",
            properties: {
              cmd: {
                type: "string",
                description: "The command to run, as in `go run ./plugins/extract-go`.",
              },
            },
          },
        },
      },
      ...defs,
    },
  };
}

/** The schema for one step of a phase, with the options of each plugin that belongs in it. */
function step(phase) {
  const names = [...described]
    .filter(([, descriptor]) => !descriptor || (descriptor.phases ?? []).includes(phase))
    .map(([name]) => name);

  const reads = phase !== "generate";

  return {
    type: "object",
    additionalProperties: false,
    required: reads ? ["plugin", "in", "out"] : ["plugin", "out"],
    properties: {
      plugin: {
        // The enum is the declared names, not the plugins' own, and it leaves
        // out the ones that do not belong in this phase: an extractor offered
        // where a renderer goes is a step that would fail with nothing to read.
        enum: names,
        description: "A plugin declared above, one that belongs in this phase.",
      },
      ...(reads
        ? {
            in: {
              type: "string",
              description: "The directory to read, relative to the repository.",
            },
          }
        : {}),
      out: {
        type: "string",
        description:
          "Where what comes back is written. A plugin names files; nothing it names is allowed to land outside this directory.",
      },
      options: {
        type: "object",
        description: "Passed to the plugin unread. What it accepts is described below.",
      },
    },
    // One branch per plugin, so the options offered are the ones that plugin
    // takes. A plugin that does not describe itself has no branch, and its
    // options go unchecked rather than being refused.
    allOf: names
      .filter((name) => described.get(name)?.options)
      .map((name) => ({
        if: { required: ["plugin"], properties: { plugin: { const: name } } },
        then: {
          properties: {
            options: { $ref: `#/$defs/${pointer(optionsKey(name))}` },
          },
        },
      })),
  };
}

function optionsKey(name) {
  return `options.${name}`;
}

/** Escapes a $defs key for the JSON pointer that refers to it. */
function pointer(key) {
  return encodeURIComponent(key.replaceAll("~", "~0").replaceAll("/", "~1"));
}

function fail(message) {
  console.error(`portolan schema: ${message}`);
  process.exit(1);
}
