// Composes the JSON Schema for portolan.json out of what the plugins say about
// themselves.
//
//   node scripts/schema.mjs            write schema/portolan.schema.json and
//                                      src/lib/plugin-index.json
//   node scripts/schema.mjs --check    fail if either file on disk is not what
//                                      the plugins describe now
//
// The manifest tells each plugin the things its source cannot carry - which
// bounded context a Go module belongs to, whose proto package a client calls.
// Only the plugin knows what it can be told, so it is asked, and the answers
// are composed into one document keyed by the name the manifest declares each
// plugin under. An editor reads it while the file is being written; `gen` reads
// it before running anything.
//
// The result is committed, which is what keeps `gen` from having to ask four
// plugins the same question on every run. `--check` in CI is what keeps the
// committed copy honest.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

import { describePlugin } from "./plugin-host.mjs";

const OUT = "schema/portolan.schema.json";
const INDEX = "src/lib/plugin-index.json";

const check = process.argv.includes("--check");
// Bootstrap exception: this command produces the schema that loadManifest
// validates against, so requiring the previous schema here would make a new
// manifest field impossible to introduce. Every consumer of the composed
// schema goes through scripts/manifest.mjs.
const manifest = JSON.parse(readFileSync("portolan.json", "utf8"));

const described = new Map();
for (const plugin of manifest.plugins ?? []) {
  let descriptor;
  try {
    descriptor = await describePlugin(plugin);
  } catch (cause) {
    fail(`plugin ${plugin.name} could not be asked what it is: ${cause.message}`);
  }

  if (!descriptor) {
    // A plugin from before this part of the protocol existed. Naming it in the
    // manifest is not an error; it just means its options are the one thing
    // here nothing can check.
    console.warn(
      `  ${plugin.name} does not describe itself, so its options are not checked`,
    );
  }

  described.set(plugin.name, descriptor);
}

const composed = `${JSON.stringify(compose(), null, 2)}\n`;
const index = `${JSON.stringify(pluginIndex(), null, 2)}\n`;

let stale = false;
for (const [path, contents, directory] of [
  [OUT, composed, "schema"],
  [INDEX, index, "src/lib"],
]) {
  let current = null;
  try {
    current = readFileSync(path, "utf8");
  } catch {
    // Absent, which is the same as out of date.
  }

  if (current === contents) {
    console.log(`${path}: up to date`);
  } else if (check) {
    console.error(
      `${path} is ${current === null ? "missing" : "out of date"}. Run \`npm run schema\`.`,
    );
    stale = true;
  } else {
    mkdirSync(directory, { recursive: true });
    writeFileSync(path, contents);
    console.log(`${path}: written from ${described.size} plugin${described.size === 1 ? "" : "s"}`);
  }
}
if (stale) process.exit(1);

/**
 * The plugin index: every plugin the package ships, as it describes itself,
 * with how the manifest runs it. The site's /plugins page and the landing's
 * list of inputs are rendered from this, so a plugin added to portolan.json
 * appears there without anyone writing it down twice. Kept under src/ rather
 * than beside the schema because the staged site copies src/ and nothing else.
 */
function pluginIndex() {
  const out = [];
  for (const plugin of manifest.plugins ?? []) {
    const descriptor = described.get(plugin.name);
    if (!descriptor) continue;
    out.push({
      name: plugin.name,
      plugin: descriptor.name,
      summary: descriptor.summary,
      category: descriptor.category,
      phases: descriptor.phases,
      ...(descriptor.needs?.length ? { needs: descriptor.needs } : {}),
      runtime: plugin.wasm ? "wasm" : plugin.host ? "host" : "process",
      // The toolchain a process plugin asks the build for; the sandboxed
      // module and the host's own code ask for nothing.
      ...(plugin.process ? { toolchain: plugin.process.command } : {}),
      source: plugin.host
        ? `scripts/host-plugins/${plugin.host}.mjs`
        : `plugins/${descriptor.name}`,
      options: descriptor.options ?? {},
    });
  }
  return out;
}

function compose() {
  const defs = {};
  for (const [name, descriptor] of described) {
    if (descriptor?.options) defs[optionsKey(name)] = descriptor.options;
  }

  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://github.com/shortlink-org/portolan/schema/portolan.schema.json",
    title: "portolan manifest",
    description:
      "Where the facts come from, what produces them, and what turns them into something to read. Generated by scripts/schema.mjs from the plugins this manifest declares; run `npm run schema` after changing them.",
    type: "object",
    additionalProperties: false,
    required: ["sources"],
    properties: {
      $schema: { type: "string" },
      $comment: { type: "string" },
      sources: {
        type: "array",
        minItems: 1,
        items: { type: "string" },
        description:
          "Globs of the catalog fragments that make up the estate. They are merged, then validated as a union, so a fragment naming a peer it does not own is normal rather than broken.",
      },
      defaultCatalog: {
        type: "string",
        minLength: 1,
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
        description: "Catalog profile selected when the URL does not name one.",
      },
      catalogs: {
        type: "array",
        minItems: 1,
        items: { $ref: "#/$defs/catalogProfile" },
        description:
          "Independent presentations of the available fragments. Each profile is merged, enriched and validated on its own.",
      },
      projects: {
        type: "array",
        items: { $ref: "#/$defs/project" },
        description:
          "The source projects that make up the estate. A project gives repeated pipeline inputs one name for the generated site's Settings page; estate-wide inputs such as flows need no project.",
      },
      warningPolicies: {
        type: "array",
        maxItems: 100,
        items: { $ref: "#/$defs/warningPolicy" },
        description:
          "CEL policies for reviewed extraction limitations. Expressions are type-checked when the manifest is read and suppression always requires a reason.",
      },
      plugins: {
        type: "array",
        items: { $ref: "#/$defs/plugin" },
        description: "How to run each plugin. A step names one by the name declared here.",
      },
      extract: {
        type: "array",
        items: step("extract"),
        description: "Steps that read source and write catalog fragments. They run first, before there is a catalog.",
      },
      verify: {
        type: "array",
        items: step("verify"),
        description:
          "Steps that read something observed - traces, a test's record - and answer with a fragment about the catalog somebody else declared.",
      },
      generate: {
        type: "array",
        items: step("generate"),
        description: "Steps that read the merged catalog and write something to read.",
      },
    },
    $defs: {
      warningPolicy: {
        type: "object",
        additionalProperties: false,
        required: ["when", "action", "reason"],
        properties: {
          when: {
            type: "string",
            minLength: 1,
            maxLength: 1000,
            description: "Boolean CEL expression over plugin, rule, severity, project, phase, ref, message and count.",
          },
          action: {
            const: "suppress",
            description: "Suppress matching diagnostics from the active view while retaining them in the report.",
          },
          reason: {
            type: "string",
            minLength: 1,
            description: "Why this limitation is consciously accepted.",
          },
        },
      },
      catalogProfile: {
        type: "object",
        additionalProperties: false,
        required: ["id", "title", "sources", "contexts", "projects"],
        properties: {
          id: {
            type: "string",
            minLength: 1,
            pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
            description: "Stable profile id used in URLs and generator steps.",
          },
          title: { type: "string", minLength: 1 },
          sources: {
            type: "array",
            minItems: 1,
            items: { type: "string" },
            description: "Catalog fragment globs merged for this profile.",
          },
          contexts: {
            type: "array",
            minItems: 1,
            items: { type: "string", minLength: 1 },
            description: "Top-level catalog groups visible in this profile.",
          },
          projects: {
            type: "array",
            items: { type: "string", minLength: 1 },
            description: "Project ids belonging to this profile.",
          },
        },
      },
      project: {
        type: "object",
        additionalProperties: false,
        required: ["id", "name", "root"],
        properties: {
          id: {
            type: "string",
            minLength: 1,
            pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
            description: "Stable id used to associate pipeline inputs with this project.",
          },
          name: {
            type: "string",
            minLength: 1,
            description: "Human-readable project name shown in the generated site.",
          },
          root: {
            type: "string",
            minLength: 1,
            description: "Repository-relative root. A pipeline input at or below this path belongs to the project.",
          },
          context: {
            type: "string",
            minLength: 1,
            description: "Legacy alias for group. Kept so existing manifests remain valid.",
          },
          service: {
            type: "string",
            minLength: 1,
            description: "Legacy alias for component. Kept so existing manifests remain valid.",
          },
          group: {
            type: "string",
            minLength: 1,
            description: "Neutral top-level group this project contributes to.",
          },
          component: {
            type: "string",
            minLength: 1,
            description: "Component slug inside the group.",
          },
          components: {
            type: "array",
            minItems: 2,
            uniqueItems: true,
            items: { type: "string", minLength: 1 },
            description: "Deployable component slugs discovered inside one repository-backed project.",
          },
          groupKind: {
            enum: ["bounded-context", "system", "product", "team", "namespace"],
            description: "Semantic role of the project's top-level group.",
          },
          componentKind: {
            enum: ["service", "application", "webapp", "worker", "job", "function", "cli", "library", "data-pipeline"],
            description: "Runtime or code role of the project component.",
          },
          repository: {
            type: "string",
            minLength: 1,
            description: "Repository page or clone URL, when the project comes from another repository.",
          },
        },
      },
      plugin: {
        type: "object",
        additionalProperties: false,
        required: ["name"],
        oneOf: [{ required: ["wasm"] }, { required: ["process"] }, { required: ["host"] }],
        properties: {
          name: {
            type: "string",
            description: "What the steps below call this plugin. It need not be the plugin's own name.",
          },
          host: {
            enum: ["fetch-git", "fetch-bsr", "fetch-csr", "fetch-k8s", "fetch-argocd"],
            description:
              "A plugin the host runs inside its own process, because it needs a socket or a git binary (portolan.0008). Only the ones shipped with Portolan can be named.",
          },
          wasm: {
            type: "object",
            additionalProperties: false,
            required: ["url"],
            description:
              "The default. The module gets no filesystem, no network and no environment, so a plugin from somebody else's repository can be run over your source tree without reading it.",
            properties: {
              url: {
                type: "string",
                pattern: "^(https://|file://)",
                description:
                  "https:// to download, or file:// for a path beside the manifest, as in file://plugins/gen-markdown.wasm.",
              },
              sha256: {
                type: "string",
                pattern: "^[0-9a-f]{64}$",
                description:
                  "Checksum of the module. Required for a download; optional for a local file, which it does not protect.",
              },
            },
          },
          process: {
            type: "object",
            additionalProperties: false,
            required: ["command"],
            description:
              "The escape hatch for a plugin that needs a toolchain. Same protocol, none of the sandbox, which is the trade being made.",
            properties: {
              command: {
                type: "string",
                minLength: 1,
                description: "The executable to run. It is passed directly to the OS, never through a shell.",
              },
              args: {
                type: "array",
                items: { type: "string" },
                description: "Arguments passed to the executable without shell parsing.",
              },
            },
          },
        },
      },
      ...defs,
    },
  };
}

/** The schema for one step of a phase, with the options of each plugin that belongs in it. */
function step(phase) {
  const names = [...described]
    .filter(([, descriptor]) => !descriptor || (descriptor.phases ?? []).includes(phase))
    .map(([name]) => name);

  const reads = phase !== "generate";

  return {
    type: "object",
    additionalProperties: false,
    required: reads ? ["plugin", "in", "out"] : ["plugin", "out"],
    properties: {
      plugin: {
        // The enum is the declared names, not the plugins' own, and it leaves
        // out the ones that do not belong in this phase: an extractor offered
        // where a renderer goes is a step that would fail with nothing to read.
        enum: names,
        description: "A plugin declared above, one that belongs in this phase.",
      },
      ...(!reads
        ? {
            catalog: {
              type: "string",
              minLength: 1,
              description: "Catalog profile supplied to this generator.",
            },
          }
        : {}),
      ...(reads
        ? {
            in: {
              type: "string",
              description: "The directory to read, relative to the repository.",
            },
          }
        : {}),
      out: {
        type: "string",
        description:
          "Where what comes back is written. A plugin names files; nothing it names is allowed to land outside this directory.",
      },
      options: {
        type: "object",
        description: "Passed to the plugin unread. What it accepts is described below.",
      },
    },
    // One branch per plugin, so the options offered are the ones that plugin
    // takes. A plugin that does not describe itself has no branch, and its
    // options go unchecked rather than being refused.
    allOf: names
      .filter((name) => described.get(name)?.options)
      .map((name) => ({
        if: { required: ["plugin"], properties: { plugin: { const: name } } },
        then: {
          properties: {
            options: { $ref: `#/$defs/${pointer(optionsKey(name))}` },
          },
        },
      })),
  };
}

function optionsKey(name) {
  return `options.${name}`;
}

/** Escapes a $defs key for the JSON pointer that refers to it. */
function pointer(key) {
  return encodeURIComponent(key.replaceAll("~", "~0").replaceAll("/", "~1"));
}

function fail(message) {
  console.error(`portolan schema: ${message}`);
  process.exit(1);
}
