// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package check_credentials_test

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLockout creates a new instance of MockLockout. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLockout(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLockout {
	mock := &MockLockout{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLockout is an autogenerated mock type for the Lockout type
type MockLockout struct {
	mock.Mock
}

type MockLockout_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLockout) EXPECT() *MockLockout_Expecter {
	return &MockLockout_Expecter{mock: &_m.Mock}
}

// Allowed provides a mock function for the type MockLockout
func (_mock *MockLockout) Allowed(ctx context.Context, userID string) (bool, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Allowed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLockout_Allowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allowed'
type MockLockout_Allowed_Call struct {
	*mock.Call
}

// Allowed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockLockout_Expecter) Allowed(ctx any, userID any) *MockLockout_Allowed_Call {
	return &MockLockout_Allowed_Call{Call: _e.mock.On("Allowed", ctx, userID)}
}

func (_c *MockLockout_Allowed_Call) Run(run func(ctx context.Context, userID string)) *MockLockout_Allowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLockout_Allowed_Call) Return(b bool, err error) *MockLockout_Allowed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockLockout_Allowed_Call) RunAndReturn(run func(ctx context.Context, userID string) (bool, error)) *MockLockout_Allowed_Call {
	_c.Call.Return(run)
	return _c
}

// Failed provides a mock function for the type MockLockout
func (_mock *MockLockout) Failed(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Failed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLockout_Failed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Failed'
type MockLockout_Failed_Call struct {
	*mock.Call
}

// Failed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockLockout_Expecter) Failed(ctx any, userID any) *MockLockout_Failed_Call {
	return &MockLockout_Failed_Call{Call: _e.mock.On("Failed", ctx, userID)}
}

func (_c *MockLockout_Failed_Call) Run(run func(ctx context.Context, userID string)) *MockLockout_Failed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLockout_Failed_Call) Return(err error) *MockLockout_Failed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLockout_Failed_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockLockout_Failed_Call {
	_c.Call.Return(run)
	return _c
}

// Succeeded provides a mock function for the type MockLockout
func (_mock *MockLockout) Succeeded(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Succeeded")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLockout_Succeeded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Succeeded'
type MockLockout_Succeeded_Call struct {
	*mock.Call
}

// Succeeded is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockLockout_Expecter) Succeeded(ctx any, userID any) *MockLockout_Succeeded_Call {
	return &MockLockout_Succeeded_Call{Call: _e.mock.On("Succeeded", ctx, userID)}
}

func (_c *MockLockout_Succeeded_Call) Run(run func(ctx context.Context, userID string)) *MockLockout_Succeeded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLockout_Succeeded_Call) Return(err error) *MockLockout_Succeeded_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLockout_Succeeded_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *MockLockout_Succeeded_Call {
	_c.Call.Return(run)
	return _c
}
