// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package check_credentials_test

import (
	"github.com/shortlink-org/portolan/examples/auth/internal/user/domain/vo/password"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPasswordVerifier creates a new instance of MockPasswordVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordVerifier {
	mock := &MockPasswordVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordVerifier is an autogenerated mock type for the PasswordVerifier type
type MockPasswordVerifier struct {
	mock.Mock
}

type MockPasswordVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordVerifier) EXPECT() *MockPasswordVerifier_Expecter {
	return &MockPasswordVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function for the type MockPasswordVerifier
func (_mock *MockPasswordVerifier) Verify(plaintext string, hash password.Hash) bool {
	ret := _mock.Called(plaintext, hash)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, password.Hash) bool); ok {
		r0 = returnFunc(plaintext, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPasswordVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockPasswordVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - plaintext string
//   - hash password.Hash
func (_e *MockPasswordVerifier_Expecter) Verify(plaintext any, hash any) *MockPasswordVerifier_Verify_Call {
	return &MockPasswordVerifier_Verify_Call{Call: _e.mock.On("Verify", plaintext, hash)}
}

func (_c *MockPasswordVerifier_Verify_Call) Run(run func(plaintext string, hash password.Hash)) *MockPasswordVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 password.Hash
		if args[1] != nil {
			arg1 = args[1].(password.Hash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordVerifier_Verify_Call) Return(b bool) *MockPasswordVerifier_Verify_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPasswordVerifier_Verify_Call) RunAndReturn(run func(plaintext string, hash password.Hash) bool) *MockPasswordVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}
