// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
)

const getOrder = `-- name: GetOrder :one
SELECT id, state FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(&i.ID, &i.State)
	return i, err
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO orders (id, state) VALUES ($1, $2)
`

func (q *Queries) InsertOrder(ctx context.Context, id string, state string) error {
	_, err := q.db.ExecContext(ctx, insertOrder, id, state)
	return err
}

const deleteOrderLines = `-- name: DeleteOrderLines :exec
DELETE FROM order_lines WHERE order_id = $1
`

func (q *Queries) DeleteOrderLines(ctx context.Context, orderID string) error {
	_, err := q.db.ExecContext(ctx, deleteOrderLines, orderID)
	return err
}

type Order struct {
	ID    string
	State string
}
